// 2026 cap snapshot. Numbers are approximate live-field reports, refreshed daily.

export const CAP_STATE = {
  year: 2026,
  capSpaceOTC: 30_400_000,      // Over The Cap (approx, post-Pitts extension Jun 23: OTC pegged ~$11.06M freed vs the $14.12M tag)
  capSpaceSpotrac: 29_900_000,  // Spotrac top-51 (approx, post-Pitts extension; prior post-London/Morris base +~$11M from the tag-to-deal swap)
  leagueRank: 21,
  totalLiabilities: 295_650_548,
  totalAllocations: 268_323_031,
  deadMoney: {
    total: 39_000_000,
    breakdown: [
      { name: "Kirk Cousins", amount: 22_500_000, note: "Released w/ post-June-1 designation; $12.5M more dead in 2027" },
      { name: "Darnell Mooney", amount: 11_000_000, note: "Released Mar 9 (pre-June 1); $7.42M cap savings" },
      { name: "Various pre-2026 cuts", amount: 5_500_000, note: "Aggregated" },
    ],
  },
  topCapHits2026: [
    { playerId: "lindstrom", amount: 19500000 },
    { playerId: "terrell", amount: 19200000 },
    { playerId: "bates", amount: 16800000 },
    { playerId: "drake-london", amount: 16800000 },
    { playerId: "matthews", amount: 15500000 },
  ],
  pendingExtensions: [],
  restructureCandidates: [
    {
      playerId: "lindstrom",
      maxSavings: 9_000_000,
      note: "Already did 1 restructure; room for another simple convert",
    },
    {
      playerId: "bates",
      maxSavings: 7_500_000,
      note: "Standard conversion if more room needed",
    },
  ],
  recentMoves: [
    { date: "2026-08-18", description: "Signed three-time Pro Bowl EDGE Za'Darius Smith to a one-year deal worth $6M and up to $8M with incentives, a day before the Colts joint practices. Smith, 33, un-retires after leaving the game in October 2025 following five games with the Eagles; the reunion with HC Kevin Stefanski, who coached him in Cleveland in 2023-24, helped Atlanta beat out the Browns after a workout. The signing answers a gutted edge room (Jalon Walker's season-ending ACL, James Pearce Jr.'s eight-game ban) and slots him into the rotation with Ebukam, Ojulari, Cameron Thomas and Dorlus. Modest 2026 cap charge against the ~$29-30M top-51 space" },
    { date: "2026-08-14", description: "NFL suspended EDGE James Pearce Jr. for the first 8 games of 2026 for violating the Personal Conduct Policy, announced hours before the preseason opener. The ban starts Aug 30 (also the 53-man cutdown deadline), and he is eligible to return Nov 2, the week of the Bengals game in Madrid. Pearce can play the preseason and stay with the team until then. He forfeits 8 game checks; his rookie-scale cap number is otherwise unaffected. Paired with Jalon Walker's season-ending ACL, it leaves the edge room leaning on Ebukam, Ojulari, Cameron Thomas, Brandon Dorlus and Zach Harrison to open the year" },
    { date: "2026-08-12", description: "Bottom-of-roster reshuffle two days before the preseason opener: signed RB Trey Sermon (Marietta native, ex-Ohio State) for backfield depth, signed TE Nick Muse while waiving/injuring WR Le'Meke Brockington and LB Malik Verdon, and claimed OL Jaeden Roberts (Alabama UDFA, ex-Eagles) off waivers. Released LB Troy Andersen, the 2022 second-round pick whose three seasons were repeatedly interrupted by injury. All minimum-salary or waiver moves, negligible cap impact" },
    { date: "2026-08-10", description: "Signed veteran DE Cameron Sample (Snellville native, 2021 Bengals fourth-rounder, most recently San Francisco) and activated RT Jawaan Taylor off the PUP list to rejoin the right-tackle competition. In the corresponding move, placed EDGE DeAngelo Malone on Reserve/PUP, out for the 2026 season. Sample is a minimum-salary depth add for an edge room down Jalon Walker for the year and bracing for a possible James Pearce Jr. suspension; negligible cap impact" },
    { date: "2026-08-06", description: "Placed EDGE Jalon Walker on injured reserve, ending his 2026 season after tests confirmed the torn ACL suffered on the non-contact Day 6 fall, and signed DB Keidron Smith in the corresponding roster move. The IR placement guts an edge room already bracing for a possible James Pearce Jr. suspension and pushes Samson Ebukam, Azeez Ojulari, Cameron Thomas and the returning Bralen Trice into larger roles. Walker's rookie-scale cap number stays on the books; no cap relief from an in-season IR designation" },
    { date: "2026-08-04", description: "EDGE Jalon Walker feared to have torn his ACL in the Day 6 practice; carted off after a non-contact fall in an 11-on-11 two-minute drill. NFL Network reported the team fears a torn ACL and The Athletic's Josh Kendall reported a tear the same evening, pending an MRI. A confirmed tear ends his 2026 season and would send the 2025 first-round pick to IR, thinning an edge room already bracing for a possible James Pearce Jr. suspension" },
    { date: "2026-08-04", description: "Signed RB Bijan Robinson to a three-year extension worth up to $75M, making him the highest-paid running back in NFL history: $51M guaranteed and $37M at signing, the most ever guaranteed to a back, running through 2030. Ends a five-day camp hold-in. Negotiated by Nicole Lynn (Klutch Sports). Fourth core Cunningham-era extension after London, Pitts and Bergeron; signing-bonus proration raises the 2026 cap hit modestly off his prior $3.24M base" },
    { date: "2026-08-01", description: "Signed LG Matthew Bergeron to a 4yr/$96M extension ($60M guaranteed, $24M APY) running through 2030, announced Saturday. The 2023 second-round pick has started all 49 of his games across three seasons and would have hit free agency after this year. GM Ian Cunningham called him 'the type of player you build around' and 'a cornerstone of our offensive line.' It is the third core Cunningham-era extension in two months after Drake London and Kyle Pitts Sr., and it reinforces that Bijan Robinson is the next domino. Modest 2026 cap impact from signing-bonus proration" },
    { date: "2026-07-29", description: "Signed veteran QB Cooper Rush and released QB Trevor Siemian with a non-football injury designation, both on the morning of the first camp practice. With Tua Tagovailoa held out (back) and Michael Penix Jr. still limited (ACL), the room needed a healthy veteran arm; Rush, 32, went 9-5 as a spot starter in Dallas and backed up Lamar Jackson in Baltimore in 2025. Minimum-salary signing, negligible cap impact" },
    { date: "2026-06-23", description: "Signed TE Kyle Pitts Sr. to a 3yr/$54M extension ($36M fully guaranteed, $18M APY, 3rd among TEs behind Kittle and McBride; largest 3-year TE deal in NFL history per his agency). Rips up the $15.05M franchise tag, runs through 2028. OTC pegged ~$11M in 2026 cap savings vs the tag. Second core extension in three weeks after London; sets up Bijan Robinson next" },
    { date: "2026-06-17", description: "Signed three 2026 UFL standouts as minicamp closed: DE Keshawn Banks (5 sacks, 11 TFL for Orlando), DT Devonnsha Maxwell (UFL-champion DC Defenders, Georgia native), WR Antwane Wells Jr. (ex-Giants, Columbus). Released WR Casey Washington, DL Elijah Garcia and LB CJ Nunnally IV in corresponding moves. Minimum-salary depth signings, negligible cap impact" },
    { date: "2026-06-11", description: "Acquired OT Wanya Morris and a 2027 7th-round pick from Kansas City for a 2027 6th-round pick; adds a 25-year-old swing tackle with 16 career starts (11 at LT in 2024) after McGary's retirement and Storm Norton's PUP placement. Morris is on the final year of his rookie deal, about a $1.71M cap hit, no guaranteed money left" },
    { date: "2026-06-09", description: "WR Drake London officially signs the 4yr/$141M extension (agreed Jun 2) at a Flowery Branch press conference; 'I know it's a lot of money, and I've got to prove it still'" },
    { date: "2026-06-02", description: "Signed WR Drake London to a 4yr/$141M extension (up to $150M w/ incentives, $100M gtd, $35.25M APY — 3rd-highest WR); runs through 2030, 2026 still on $16.82M 5th-yr option. First major deal of the Cunningham/Ryan front office" },
    { date: "2026-06-01", description: "Kirk Cousins post-June-1 designation officially clears +$2.1M in 2026 and +$45M in 2027 cap space (OTC); dead money tail is $22.5M in 2026, $12.5M in 2027" },
    { date: "2026-05-14", description: "Signed CB Darren Hall (2021 R4 reunion, vet stops IND/ARI); released S Tysheem Johnson in corresponding move" },
    { date: "2026-05-12", description: "Signed DT Ross Blacklock, OL Brandon Walton, G Layden Robinson, LB Daveren Rayner off rookie-minicamp tryouts; released DL Ben Stille, RB Carlos Washington Jr., WR Deven Thompkins, TE Brandon Frazier" },
    { date: "2026-05-07", description: "Signed 14 UDFAs (QB Strand, C Brockermeyer, DT Allen, OT Mahlman, G Dewberry, WRs Marion / Rutherford / V. Anthony / A. Anthony / Brockington, RB Cash Jones, TE Velling, DL Nunnally IV, CB Dewalt IV)" },
    { date: "2026-04-17", description: "Traded DT Ruke Orhorhoro to JAX for DT Maason Smith (player-for-player)" },
    { date: "2026-04-12", description: "Exercised Bijan Robinson's 5th-year option ($11.32M in 2027)" },
    { date: "2026-04-09", description: "Signed OT Jawaan Taylor (1yr/$5M + $1M incentives) as McGary replacement" },
    { date: "2026-04-08", description: "RT Kaleb McGary retires — frees ~$14M across 2026–2027" },
    { date: "2026-03-20", description: "Traded picks 114 + 197 to PHI for S Sydney Brown + picks 122 + 215" },
    { date: "2026-03-14", description: "Placed franchise tag on Kyle Pitts ($14.1M)" },
    { date: "2026-03-13", description: "EDGE Arnold Ebiketie signs 1yr / $7.3M max with Philadelphia Eagles" },
    { date: "2026-03-12", description: "Slot CB Dee Alford signs 3yr / $21M max with Buffalo Bills" },
    { date: "2026-03-11", description: "LB Kaden Elliss signs 3yr/$33M ($23M gtd) with New Orleans Saints" },
    { date: "2026-03-11", description: "Released Kirk Cousins (league year start)" },
    { date: "2026-03-10", description: "Signed DT Da'Shawn Hand (1yr / $3M) — partial Onyemata replacement" },
    { date: "2026-03-10", description: "DT David Onyemata signs with New York Jets in free agency" },
    { date: "2026-03-10", description: "RB Tyler Allgeier signs with Arizona Cardinals in free agency" },
    { date: "2026-03-09", description: "Released WR Darnell Mooney ($7.42M cap savings, ~$11M dead money)" },
    { date: "2026-03-09", description: "Released WR KhaDarel Hodge ($3.3M cap savings)" },
    { date: "2026-03-08", description: "Restructured Jake Matthews — cleared $10.5M" },
  ],
};
