// 2026 NFL Draft — Falcons-specific data.
// Refreshed by the scheduled task (manual runs recommended during Apr 23–25).

export const DRAFT_DATA = {
  draftYear: 2026,
  startTime: "2026-04-23T20:00:00-04:00", // Round 1, Thursday
  location: "Acrisure Stadium · Pittsburgh",
  tvChannels: ["NFL Network", "ESPN", "ABC", "NFL+"],
  generalNote:
    "DRAFT COMPLETE · 2026 class wrapped at 12:24 AM ET Sunday. Six rookies via the board after Cunningham traded back from #122 to bank an extra Day 3 pick. Final class: R2 #48 Avieon Terrell (CB, Clemson — A.J.'s brother, A/A+ unanimity), R3 #79 Zachariah Branch (WR, Georgia — slot/returner, elite YAC), R4 #134 Kendal Daniels (LB, Oklahoma — 6'4 hybrid Cheetah, fills the Elliss hole; pick acquired from LV for #122), R6 #208 Anterio Thompson (DT, Washington — 4.73 forty at 306, 3 blocked punts; from LV), R6 #215 Harold Perkins Jr. (LB, LSU — former 1st-round talent off ACL, 4.45 forty; from PHI), R7 #231 Ethan Onianwa (OT, Ohio State — 6'6 / 333, raw OT depth behind Matthews/Taylor). National grade panorama (Mon Apr 27): NFL.com Reuter B-, CBS Bahns B+, consensus B / B+ — edge-rusher gap is the chief critique. Priority UDFA wave hardened overnight: DT Carlos Allen, C James Brockermeyer, RB Cash Jones, OL Kam Dewberry, OT Riley Mahlman, WRs Vinny Anthony II / Malik Rutherford / Keelan Marion. Rookie minicamp locked for May 8–11 at Flowery Branch.",

  // The Falcons' 5 picks
  falconsPicks: [
    {
      round: 2,
      overallPick: 48,
      status: "made", // scheduled | on-clock | made | traded
      slotEstTime: "2026-04-24T19:20:00-04:00",
      valueChart: "most-valuable-slot", // narrative label
      selection: "Avieon Terrell · CB · Clemson",
      selectionNote: "Brother of A.J. Terrell — first known starting-CB sibling tandem in NFL history. A+ grades across most outlets; slid out of R1 after re-aggravating a hamstring at his pro day.",
      tradeNote: null,
    },
    {
      round: 3,
      overallPick: 79,
      status: "made",
      slotEstTime: "2026-04-24T22:00:00-04:00",
      valueChart: "value-territory",
      selection: "Zachariah Branch · WR · Georgia",
      selectionNote: "Slot receiver / dual-threat returner. 6 TDs as a UGA junior; 78% of career yards came after the catch. Local Bulldog pick fits Stefanski's culture reset.",
      tradeNote: null,
    },
    {
      round: 4,
      overallPick: 122,
      status: "traded",
      slotEstTime: "2026-04-25T13:00:00-04:00",
      valueChart: "day-3",
      selection: null,
      tradeNote: "Originally from PHI (Sydney Brown trade). Sent to Las Vegas on Day 3 in exchange for #134 + #208 — Cunningham's first Atlanta trade-back.",
    },
    {
      round: 4,
      overallPick: 134,
      status: "made",
      slotEstTime: "2026-04-25T14:30:00-04:00",
      valueChart: "day-3",
      selection: "Kendal Daniels · LB · Oklahoma",
      selectionNote: "6'4 / 222 hybrid 'Cheetah' linebacker — 97th-percentile height for the position. Started 13 games at OU after transferring from Oklahoma State, where he played safety. 53 tackles / 9 TFL / 3 PBUs in 2025. Profile fits the Elliss-shaped hole as a sub-package SAM and on STs.",
      tradeNote: "Acquired from Las Vegas (April 25, 2026 — Cunningham traded back from #122).",
    },
    {
      round: 6,
      overallPick: 208,
      status: "made",
      slotEstTime: "2026-04-25T15:45:00-04:00",
      valueChart: "day-3",
      selection: "Anterio Thompson · DT · Washington",
      selectionNote: "6'2 / 306 attack-style interior DT. 4.73 forty at his Husky pro day plus three blocked punts in 2025 — the kind of disruptive, ST-versatile flyer Ulbrich's defense rotates on early downs. Bench/PS-eligible behind Smith/Dorlus/Harrison.",
      tradeNote: "Acquired from Las Vegas (April 25, 2026 — same trade as #134).",
    },
    {
      round: 6,
      overallPick: 215,
      status: "made",
      slotEstTime: "2026-04-25T16:30:00-04:00",
      valueChart: "day-3",
      selection: "Harold Perkins Jr. · LB · LSU",
      selectionNote: "Bet-on-talent swing. Once a projected R1 pick after a freshman All-American 2022, Perkins tore his right ACL in 2024 and his 2025 production never fully returned. Still ran 4.45 (96th percentile). Hybrid Star/edge fit for sub-packages. 4yr / $4.45M rookie deal per Spotrac.",
      tradeNote: "Acquired from Eagles (March 20, 2026 — Sydney Brown trade).",
    },
    {
      round: 7,
      overallPick: 231,
      status: "made",
      slotEstTime: "2026-04-25T17:45:00-04:00",
      valueChart: "day-3",
      selection: "Ethan Onianwa · OT · Ohio State",
      selectionNote: "6'6 / 333 developmental tackle. 34 college starts at Rice before transferring to Ohio State for 2025, where he never won a starting job. Pure size/length flyer — practice-squad-ready depth behind Matthews and Taylor.",
      tradeNote: null,
    },
  ],

  // 2026 Class — drafted Falcons. Pre-draft mock board archived; cards now
  // describe the actual rookies who will report to minicamp May 1-4 / May 8-11.
  topTargets: [
    {
      id: "avieon-terrell",
      name: "Avieon Terrell",
      position: "CB",
      college: "Clemson",
      heightIn: 71,
      weight: 184,
      age: 21,
      fortyTime: 4.46,
      projection: "Drafted · R2 #48",
      fit: "A.J. Terrell's younger brother — first known starting-CB sibling tandem in NFL history. Plays bigger than 5'11 with fluid hips and read-and-drive eyes. R1 pre-combine grade; slid after a re-aggravated hamstring at his pro day.",
      strengths: ["Light-footed pedal", "Press technique", "Bloodlines + film vs SEC"],
      concerns: ["Frame", "Hamstring history into camp"],
      mockProjections: [{ source: "Atlanta · #48 actual", pick: 48 }],
      headshot: null,
    },
    {
      id: "zachariah-branch",
      name: "Zachariah Branch",
      position: "WR",
      college: "Georgia",
      heightIn: 69,
      weight: 178,
      age: 21,
      fortyTime: 4.35,
      projection: "Drafted · R3 #79",
      fit: "Slot WR / dual-threat returner. 6 TDs as a UGA junior; 2023 Jet Award winner; 78% of career yards came after the catch. With Dotson and Zaccheaus already added, gives Tommy Rees a YAC weapon between London and Pitts.",
      strengths: ["Elite YAC", "4.35 speed", "Returner value baked in"],
      concerns: ["Sub-180 frame", "Routes vs press still developing"],
      mockProjections: [{ source: "Atlanta · #79 actual", pick: 79 }],
      headshot: null,
    },
    {
      id: "kendal-daniels",
      name: "Kendal Daniels",
      position: "LB",
      college: "Oklahoma",
      heightIn: 76,
      weight: 222,
      age: 23,
      fortyTime: 4.62,
      projection: "Drafted · R4 #134",
      fit: "Hybrid 'Cheetah' linebacker — three years at Oklahoma State safety, transferred to OU for a 13-start senior year on or near the line. 97th-percentile LB height. Fills the Elliss-shaped sub-package SAM role and STs.",
      strengths: ["Length / range", "Versatility S→LB", "TFL production (9 in 2025)"],
      concerns: ["New to off-ball role", "Run fits"],
      mockProjections: [{ source: "Atlanta · #134 actual", pick: 134 }],
      headshot: null,
    },
    {
      id: "anterio-thompson",
      name: "Anterio Thompson",
      position: "DT",
      college: "Washington",
      heightIn: 74,
      weight: 306,
      age: 23,
      fortyTime: 4.73,
      projection: "Drafted · R6 #208",
      fit: "Attack-style 3-tech with rare burst for his size (4.73 at 306) and three blocked punts in 2025 — exactly the disruptive, ST-versatile flyer Ulbrich's defense rotates on passing downs.",
      strengths: ["Get-off / quickness", "Blocked-kick tape", "Pro day testing"],
      concerns: ["Modest college production", "Anchor vs NFL doubles"],
      mockProjections: [{ source: "Atlanta · #208 actual", pick: 208 }],
      headshot: null,
    },
    {
      id: "harold-perkins",
      name: "Harold Perkins Jr.",
      position: "LB",
      college: "LSU",
      heightIn: 73,
      weight: 220,
      age: 22,
      fortyTime: 4.45,
      projection: "Drafted · R6 #215",
      fit: "Bet-on-talent swing. Freshman All-American at LSU in 2022; tore his right ACL in 2024 and 2025 production lagged. 4.45 forty (96th pct LB). 4yr / $4.45M deal per Spotrac. Hybrid Star/EDGE rotation piece in sub.",
      strengths: ["Speed", "First-round burst on 2022 tape", "Position flex"],
      concerns: ["ACL recovery", "2025 regression / weight"],
      mockProjections: [{ source: "Atlanta · #215 actual", pick: 215 }],
      headshot: null,
    },
    {
      id: "ethan-onianwa",
      name: "Ethan Onianwa",
      position: "OT",
      college: "Ohio State",
      heightIn: 78,
      weight: 333,
      age: 23,
      fortyTime: 5.34,
      projection: "Drafted · R7 #231",
      fit: "Developmental swing tackle. 34 starts at Rice before transferring to OSU for 2025, where he never won a starting job. Pure size/length flyer — PS-ready depth behind Matthews and 1-yr signee Jawaan Taylor.",
      strengths: ["6'6 / 333 frame", "Long arms", "Experienced four-year starter"],
      concerns: ["Lost OSU job battle", "Foot speed"],
      mockProjections: [{ source: "Atlanta · #231 actual", pick: 231 }],
      headshot: null,
    },
  ],
};
