// 2026 NFL Draft — Falcons-specific data.
// Refreshed by the scheduled task (manual runs recommended during Apr 23–25).

export const DRAFT_DATA = {
  draftYear: 2026,
  startTime: "2026-04-23T20:00:00-04:00", // Round 1, Thursday
  location: "Acrisure Stadium · Pittsburgh",
  tvChannels: ["NFL Network", "ESPN", "ABC", "NFL+"],
  generalNote:
    "Falcons have no first-rounder (2026 R1 sent to Rams via the 2025 James Pearce Jr. trade-up). Cunningham is openly shopping #48 for additional Day 2/3 picks — he took Chicago from 5 picks to 10 his first year running their board. Former Falcons RB Michael Turner will announce Atlanta's R2 pick Friday night in Pittsburgh.",

  // The Falcons' 5 picks
  falconsPicks: [
    {
      round: 2,
      overallPick: 48,
      status: "scheduled", // scheduled | on-clock | made | traded
      slotEstTime: "2026-04-24T19:20:00-04:00",
      valueChart: "most-valuable-slot", // narrative label
      selection: null,
      tradeNote: null,
    },
    {
      round: 3,
      overallPick: 79,
      status: "scheduled",
      slotEstTime: "2026-04-24T22:00:00-04:00",
      valueChart: "value-territory",
      selection: null,
      tradeNote: null,
    },
    {
      round: 4,
      overallPick: 122,
      status: "scheduled",
      slotEstTime: "2026-04-25T13:00:00-04:00",
      valueChart: "day-3",
      selection: null,
      tradeNote: "Acquired from Eagles (March 20, 2026 — Sydney Brown trade)",
    },
    {
      round: 6,
      overallPick: 215,
      status: "scheduled",
      slotEstTime: "2026-04-25T16:30:00-04:00",
      valueChart: "day-3",
      selection: null,
      tradeNote: "Acquired from Eagles (March 20, 2026 — Sydney Brown trade)",
    },
    {
      round: 7,
      overallPick: 231,
      status: "scheduled",
      slotEstTime: "2026-04-25T17:45:00-04:00",
      valueChart: "day-3",
      selection: null,
      tradeNote: null,
    },
  ],

  // Top Falcons-fit prospects — pre-draft board.
  // Mapped against the 5 picks as best-case scenarios.
  topTargets: [
    {
      id: "branch",
      name: "Zachariah Branch",
      position: "WR",
      college: "Georgia",
      heightIn: 68.6,
      weight: 177,
      age: 21,
      fortyTime: 4.35,
      projection: "Round 2 · #48 range",
      fit: "Elite YAC + returner value. Drafts like a slot WR1 who immediately upgrades Falcons special teams. Local (UGA) tie appeals to Stefanski's culture reset.",
      strengths: ["Top-end speed", "YAC generation", "Punt/kick return upside (Jet Award 2023)"],
      concerns: ["5'8⅝, 177 lbs — sub-ideal outside frame", "Route tree needs polish"],
      mockProjections: [
        { source: "Kiper ESPN", pick: 48 },
        { source: "The Falcoholic", pick: 48 },
      ],
      headshot: null,
    },
    {
      id: "bryce-lance",
      name: "Bryce Lance",
      position: "WR",
      college: "North Dakota State",
      heightIn: 75,
      weight: 204,
      age: 22,
      fortyTime: 4.48,
      projection: "Round 2 · #48–79 range",
      fit: "Size-speed boundary WR — the opposite of Branch. Younger brother of Trey Lance. Strong vertical threat paired with Drake London would stretch defenses.",
      strengths: ["6'3 / 204 with speed", "Ball tracking + contested catch", "#2 Athleticism Score among WRs at Combine"],
      concerns: ["FCS competition level", "Route-running quickness at pro level"],
      mockProjections: [
        { source: "Bleacher Report", pick: 55 },
        { source: "Pro Football Network", pick: 48 },
        { source: "The Athletic · Brugler", pick: 79 },
      ],
      headshot: null,
    },
    {
      id: "rodriguez-lb",
      name: "Jacob Rodriguez",
      position: "LB",
      college: "Texas Tech",
      heightIn: 73,
      weight: 232,
      age: 23,
      fortyTime: 4.58,
      projection: "Round 2 · #48 range",
      fit: "Complete off-ball LB. Swept 2025 major defensive awards (Bednarik, Butkus, Lombardi, Nagurski). Immediate ILB need with Kaden Elliss gone to New Orleans in FA.",
      strengths: ["All-around production", "Instincts + vs-pass coverage", "Culture captain"],
      concerns: ["Average length", "Non-elite top-end speed"],
      mockProjections: [
        { source: "Falcoholic mock", pick: 48 },
        { source: "ESPN Reid", pick: 50 },
      ],
      headshot: null,
    },
    {
      id: "abney",
      name: "Keith Abney II",
      position: "CB",
      college: "Arizona State",
      heightIn: 72,
      weight: 190,
      age: 22,
      fortyTime: 4.46,
      projection: "Round 2 · #48 – Round 3",
      fit: "Press-man CB to pair with A.J. Terrell. 44.4% completion rate allowed in 2025. Could play slot or outside.",
      strengths: ["Press / quick decisions", "Ball production — 5 INTs in final 25 starts", "Intuition"],
      concerns: ["Aggressiveness sometimes bites him", "Size not elite"],
      mockProjections: [
        { source: "The Falcoholic", pick: 48 },
        { source: "Bleacher Report", pick: 55 },
      ],
      headshot: null,
    },
    {
      id: "bernard",
      name: "Germie Bernard",
      position: "WR",
      college: "Alabama",
      heightIn: 73,
      weight: 200,
      age: 22,
      fortyTime: 4.45,
      projection: "Round 3 · #79 range",
      fit: "Balanced three-level WR. Took a top-30 visit to Flowery Branch. Could be the #48 fallback if both Branch and Lance go early.",
      strengths: ["YAC", "Reliable hands", "Run-blocking for a WR"],
      concerns: ["Doesn't separate consistently vs man"],
      mockProjections: [{ source: "Falcons.com mock", pick: 79 }],
      headshot: null,
    },
    {
      id: "hunter-dt",
      name: "Lee Hunter",
      position: "DT",
      college: "UCF",
      heightIn: 76,
      weight: 322,
      age: 23,
      fortyTime: 5.15,
      projection: "Round 2–3",
      fit: "Beef for the trenches. Kiper's final mock sent him to Atlanta. Pairs with Dorlus / newly-acquired Maason Smith on the interior.",
      strengths: ["Size + anchor", "Twitchy for his weight"],
      concerns: ["Inconsistent pass-rush plan"],
      mockProjections: [{ source: "Kiper Final Mock", pick: 48 }],
      headshot: null,
    },
    {
      id: "christen-miller",
      name: "Christen Miller",
      position: "DT",
      college: "Georgia",
      heightIn: 75,
      weight: 305,
      age: 22,
      fortyTime: 4.97,
      projection: "Round 2 · #48 range",
      fit: "Local Bulldog with a three-down skill set. Took a top-30 visit to Flowery Branch. ESPN's Matt Miller and The Athletic's Brugler both sent him to Atlanta at #48. Fits Stefanski's stop-the-run identity reset.",
      strengths: ["Power + length", "SEC-tested against NFL-caliber OL", "High football IQ"],
      concerns: ["Production modest vs pedigree", "Rotational usage in college"],
      mockProjections: [
        { source: "ESPN Matt Miller", pick: 48 },
        { source: "The Athletic · Brugler", pick: 48 },
      ],
      headshot: null,
    },
    {
      id: "tj-parker",
      name: "T.J. Parker",
      position: "EDGE",
      college: "Clemson",
      heightIn: 76,
      weight: 260,
      age: 22,
      fortyTime: 4.6,
      projection: "Round 2 · #48 range",
      fit: "Rotational edge behind Walker / Pearce / Ebiketie. CBS Sports' Renner slotted Parker to Atlanta at 48.",
      strengths: ["Bend", "First-step get-off", "Motor"],
      concerns: ["Frame may cap run-defense upside", "Counter moves still developing"],
      mockProjections: [{ source: "CBS Sports Renner", pick: 48 }],
      headshot: null,
    },
    {
      id: "ot-target",
      name: "Chase Lundt",
      position: "OT",
      college: "UConn",
      heightIn: 79,
      weight: 310,
      age: 22,
      fortyTime: 5.18,
      projection: "Round 3 · #79",
      fit: "2026 OL class is thin — any startable tackle at 79 is value. McGary retirement leaves a depth hole behind Taylor.",
      strengths: ["Frame / length", "Technician"],
      concerns: ["G5 competition questions"],
      mockProjections: [{ source: "Falcoholic 7-rd", pick: 79 }],
      headshot: null,
    },
    {
      id: "te-sinnott",
      name: "Jaheim Bell",
      position: "TE",
      college: "Tennessee",
      heightIn: 74,
      weight: 240,
      age: 23,
      fortyTime: 4.65,
      projection: "Round 4 · #122",
      fit: "TE2 insurance behind Pitts / Hooper. Move piece in Stefanski's offense.",
      strengths: ["Versatile, H-back flex", "YAC after catch"],
      concerns: ["Inline blocking"],
      mockProjections: [{ source: "Falcoholic 7-rd", pick: 122 }],
      headshot: null,
    },
    {
      id: "late-cb",
      name: "Kalen King",
      position: "CB",
      college: "Penn State",
      heightIn: 71,
      weight: 190,
      age: 22,
      fortyTime: 4.53,
      projection: "Round 6 · #215",
      fit: "Developmental nickel corner behind Alford. Good tape 2024, tougher 2025.",
      strengths: ["Ball skills", "Press technique"],
      concerns: ["2025 tape vs SEC regressed"],
      mockProjections: [{ source: "NFL Mock DB avg", pick: 210 }],
      headshot: null,
    },
    {
      id: "late-edge",
      name: "Jah Joyner",
      position: "EDGE",
      college: "Minnesota",
      heightIn: 78,
      weight: 260,
      age: 24,
      fortyTime: 4.71,
      projection: "Round 7 · #231",
      fit: "Developmental edge bench depth behind Walker, Pearce, Ebiketie, Ojulari.",
      strengths: ["Length", "Power rush"],
      concerns: ["Bend, get-off"],
      mockProjections: [{ source: "WalterFootball", pick: 228 }],
      headshot: null,
    },
    {
      id: "udfa-wr",
      name: "Xavier Restrepo",
      position: "WR",
      college: "Miami",
      heightIn: 70,
      weight: 205,
      age: 23,
      fortyTime: 4.64,
      projection: "Round 6–7 · PUDFA",
      fit: "Slot depth / special teams.",
      strengths: ["Reliable hands", "Route savvy"],
      concerns: ["Slow 40 time hurt stock"],
      mockProjections: [{ source: "PFN", pick: 220 }],
      headshot: null,
    },
  ],
};
