// 2026 NFL Draft — Falcons-specific data.
// Refreshed by the scheduled task (manual runs recommended during Apr 23–25).

export const DRAFT_DATA = {
  draftYear: 2026,
  startTime: "2026-04-23T20:00:00-04:00", // Round 1, Thursday
  location: "Acrisure Stadium · Pittsburgh",
  tvChannels: ["NFL Network", "ESPN", "ABC", "NFL+"],
  generalNote:
    "DAY 3 — Round 4 opens at 12:00 PM ET in Pittsburgh (≈3 hrs from now). Atlanta is 2-for-2 through Day 2: Avieon Terrell (CB, Clemson) at #48 reunites the Terrell brothers for the first known starting-CB sibling tandem in NFL history (PFSN A+ / 88.5 prospect score; A or A+ across CBS, SI, The Falcoholic, 247Sports); Zachariah Branch (WR, Georgia) at #79 lands a slot/returner with elite YAC (B/B+ from analysts split on size). Three picks remain: #122 (R4, from PHI/Sydney Brown trade), #215 (R6, from PHI), #231 (R7). CBS's Saturday best-available board points Atlanta toward LB (Kaden Elliss left for NO), interior DT behind newly-acquired Maason Smith, edge rotation behind Walker/Pearce/Ojulari, and developmental OT behind Matthews/Taylor. Cunningham still has trade-down levers — he turned five Bears picks into ten his first year in Chicago. UDFA scramble starts the second the final pick lands tonight; rookie minicamp opens May 1-4 or May 8-11.",

  // The Falcons' 5 picks
  falconsPicks: [
    {
      round: 2,
      overallPick: 48,
      status: "made", // scheduled | on-clock | made | traded
      slotEstTime: "2026-04-24T19:20:00-04:00",
      valueChart: "most-valuable-slot", // narrative label
      selection: "Avieon Terrell · CB · Clemson",
      selectionNote: "Brother of A.J. Terrell — first known starting-CB sibling tandem in NFL history. A+ grades across most outlets; slid out of R1 after re-aggravating a hamstring at his pro day.",
      tradeNote: null,
    },
    {
      round: 3,
      overallPick: 79,
      status: "made",
      slotEstTime: "2026-04-24T22:00:00-04:00",
      valueChart: "value-territory",
      selection: "Zachariah Branch · WR · Georgia",
      selectionNote: "Slot receiver / dual-threat returner. 6 TDs as a UGA junior; 78% of career yards came after the catch. Local Bulldog pick fits Stefanski's culture reset.",
      tradeNote: null,
    },
    {
      round: 4,
      overallPick: 122,
      status: "scheduled",
      slotEstTime: "2026-04-25T13:00:00-04:00",
      valueChart: "day-3",
      selection: null,
      tradeNote: "Acquired from Eagles (March 20, 2026 — Sydney Brown trade)",
    },
    {
      round: 6,
      overallPick: 215,
      status: "scheduled",
      slotEstTime: "2026-04-25T16:30:00-04:00",
      valueChart: "day-3",
      selection: null,
      tradeNote: "Acquired from Eagles (March 20, 2026 — Sydney Brown trade)",
    },
    {
      round: 7,
      overallPick: 231,
      status: "scheduled",
      slotEstTime: "2026-04-25T17:45:00-04:00",
      valueChart: "day-3",
      selection: null,
      tradeNote: null,
    },
  ],

  // Top Falcons-fit prospects — Day 3 board.
  // Branch was drafted by Atlanta at #79; pre-draft cards now scoped to remaining picks.
  topTargets: [
    {
      id: "bryce-lance",
      name: "Bryce Lance",
      position: "WR",
      college: "North Dakota State",
      heightIn: 75,
      weight: 204,
      age: 22,
      fortyTime: 4.48,
      projection: "Round 2 · #48–79 range",
      fit: "Size-speed boundary WR — the opposite of Branch. Younger brother of Trey Lance. Strong vertical threat paired with Drake London would stretch defenses.",
      strengths: ["6'3 / 204 with speed", "Ball tracking + contested catch", "#2 Athleticism Score among WRs at Combine"],
      concerns: ["FCS competition level", "Route-running quickness at pro level"],
      mockProjections: [
        { source: "Bleacher Report", pick: 55 },
        { source: "Pro Football Network", pick: 48 },
        { source: "The Athletic · Brugler", pick: 79 },
      ],
      headshot: null,
    },
    {
      id: "rodriguez-lb",
      name: "Jacob Rodriguez",
      position: "LB",
      college: "Texas Tech",
      heightIn: 73,
      weight: 232,
      age: 23,
      fortyTime: 4.58,
      projection: "Round 2 · #48 range",
      fit: "Complete off-ball LB. Swept 2025 major defensive awards (Bednarik, Butkus, Lombardi, Nagurski). Immediate ILB need with Kaden Elliss gone to New Orleans in FA.",
      strengths: ["All-around production", "Instincts + vs-pass coverage", "Culture captain"],
      concerns: ["Average length", "Non-elite top-end speed"],
      mockProjections: [
        { source: "Falcoholic mock", pick: 48 },
        { source: "ESPN Reid", pick: 50 },
      ],
      headshot: null,
    },
    {
      id: "lawson-lb",
      name: "Deontae Lawson",
      position: "LB",
      college: "Alabama",
      heightIn: 74,
      weight: 235,
      age: 23,
      fortyTime: 4.62,
      projection: "Round 2 · #48",
      fit: "Jordan Reid's final ESPN mock (Apr 21) sent Lawson to Atlanta at #48 — fills the Elliss-shaped hole with a three-down SEC-tested MIKE. Pro-ready processor; Stefanski values MIKE quarterbacks who can get the defense lined up.",
      strengths: ["Instincts / pre-snap recognition", "Tackling form and finish", "SEC captain pedigree"],
      concerns: ["Athletic ceiling not elite", "Coverage range vs NFL TEs"],
      mockProjections: [
        { source: "ESPN Reid final", pick: 48 },
      ],
      headshot: null,
    },
    {
      id: "abney",
      name: "Keith Abney II",
      position: "CB",
      college: "Arizona State",
      heightIn: 72,
      weight: 190,
      age: 22,
      fortyTime: 4.46,
      projection: "Round 2 · #48 – Round 3",
      fit: "Press-man CB to pair with A.J. Terrell. 44.4% completion rate allowed in 2025. Could play slot or outside.",
      strengths: ["Press / quick decisions", "Ball production — 5 INTs in final 25 starts", "Intuition"],
      concerns: ["Aggressiveness sometimes bites him", "Size not elite"],
      mockProjections: [
        { source: "The Falcoholic", pick: 48 },
        { source: "Bleacher Report", pick: 55 },
      ],
      headshot: null,
    },
    {
      id: "bernard",
      name: "Germie Bernard",
      position: "WR",
      college: "Alabama",
      heightIn: 73,
      weight: 200,
      age: 22,
      fortyTime: 4.45,
      projection: "Round 3 · #79 range",
      fit: "Balanced three-level WR. Took a top-30 visit to Flowery Branch. Could be the #48 fallback if both Branch and Lance go early.",
      strengths: ["YAC", "Reliable hands", "Run-blocking for a WR"],
      concerns: ["Doesn't separate consistently vs man"],
      mockProjections: [{ source: "Falcons.com mock", pick: 79 }],
      headshot: null,
    },
    {
      id: "hunter-dt",
      name: "Lee Hunter",
      position: "DT",
      college: "Texas Tech",
      heightIn: 76,
      weight: 318,
      age: 23,
      fortyTime: 5.15,
      projection: "Round 2 · #48 range",
      fit: "Beef for the trenches. Anchored the nation's #1 rush defense at Texas Tech (transferred from UCF for 2025). Kiper's final mock sent him to Atlanta at 48. Pairs with Dorlus / newly-acquired Maason Smith on the interior.",
      strengths: ["Size + anchor", "Power / bull rush", "Senior Bowl invite"],
      concerns: ["Pass-rush counters limited", "Primarily a bull-rusher"],
      mockProjections: [{ source: "Kiper Final Mock", pick: 48 }],
      headshot: null,
    },
    {
      id: "christen-miller",
      name: "Christen Miller",
      position: "DT",
      college: "Georgia",
      heightIn: 75,
      weight: 305,
      age: 22,
      fortyTime: 4.97,
      projection: "Round 2 · #48 range",
      fit: "Local Bulldog with a three-down skill set. Took a top-30 visit to Flowery Branch. ESPN's Matt Miller and The Athletic's Brugler both sent him to Atlanta at #48. Fits Stefanski's stop-the-run identity reset.",
      strengths: ["Power + length", "SEC-tested against NFL-caliber OL", "High football IQ"],
      concerns: ["Production modest vs pedigree", "Rotational usage in college"],
      mockProjections: [
        { source: "ESPN Matt Miller", pick: 48 },
        { source: "The Athletic · Brugler", pick: 48 },
      ],
      headshot: null,
    },
    {
      id: "tj-parker",
      name: "T.J. Parker",
      position: "EDGE",
      college: "Clemson",
      heightIn: 76,
      weight: 260,
      age: 22,
      fortyTime: 4.6,
      projection: "Round 2 · #48 range",
      fit: "Rotational edge behind Walker / Pearce / Ojulari — Ebiketie's departure to PHI opens an immediate rotation spot. CBS Sports' Renner slotted Parker to Atlanta at 48.",
      strengths: ["Bend", "First-step get-off", "Motor"],
      concerns: ["Frame may cap run-defense upside", "Counter moves still developing"],
      mockProjections: [{ source: "CBS Sports Renner", pick: 48 }],
      headshot: null,
    },
    {
      id: "ot-target",
      name: "Chase Lundt",
      position: "OT",
      college: "UConn",
      heightIn: 79,
      weight: 310,
      age: 22,
      fortyTime: 5.18,
      projection: "Round 3 · #79",
      fit: "2026 OL class is thin — any startable tackle at 79 is value. McGary retirement leaves a depth hole behind Taylor.",
      strengths: ["Frame / length", "Technician"],
      concerns: ["G5 competition questions"],
      mockProjections: [{ source: "Falcoholic 7-rd", pick: 79 }],
      headshot: null,
    },
    {
      id: "te-sinnott",
      name: "Jaheim Bell",
      position: "TE",
      college: "Tennessee",
      heightIn: 74,
      weight: 240,
      age: 23,
      fortyTime: 4.65,
      projection: "Round 4 · #122",
      fit: "TE2 insurance behind Pitts / Hooper. Move piece in Stefanski's offense.",
      strengths: ["Versatile, H-back flex", "YAC after catch"],
      concerns: ["Inline blocking"],
      mockProjections: [{ source: "Falcoholic 7-rd", pick: 122 }],
      headshot: null,
    },
    {
      id: "late-cb",
      name: "Kalen King",
      position: "CB",
      college: "Penn State",
      heightIn: 71,
      weight: 190,
      age: 22,
      fortyTime: 4.53,
      projection: "Round 6 · #215",
      fit: "Developmental nickel corner behind Alford. Good tape 2024, tougher 2025.",
      strengths: ["Ball skills", "Press technique"],
      concerns: ["2025 tape vs SEC regressed"],
      mockProjections: [{ source: "NFL Mock DB avg", pick: 210 }],
      headshot: null,
    },
    {
      id: "late-edge",
      name: "Jah Joyner",
      position: "EDGE",
      college: "Minnesota",
      heightIn: 78,
      weight: 260,
      age: 24,
      fortyTime: 4.71,
      projection: "Round 7 · #231",
      fit: "Developmental edge bench depth behind Walker, Pearce, Ojulari. Ebiketie's departure to PHI means PS flyer material needs less projection.",
      strengths: ["Length", "Power rush"],
      concerns: ["Bend, get-off"],
      mockProjections: [{ source: "WalterFootball", pick: 228 }],
      headshot: null,
    },
    {
      id: "udfa-wr",
      name: "Xavier Restrepo",
      position: "WR",
      college: "Miami",
      heightIn: 70,
      weight: 205,
      age: 23,
      fortyTime: 4.64,
      projection: "Round 6–7 · PUDFA",
      fit: "Slot depth / special teams.",
      strengths: ["Reliable hands", "Route savvy"],
      concerns: ["Slow 40 time hurt stock"],
      mockProjections: [{ source: "PFN", pick: 220 }],
      headshot: null,
    },
  ],
};
