// Offseason + season milestones, in chronological order.
// Used by the calendar mini-card and by the phase engine indirectly.

export const OFFSEASON_CALENDAR = [
  {
    id: "offseason-program-start",
    date: "2026-04-20T09:00:00-04:00",
    label: "Offseason program opens (Phase 1)",
    detail: "First day of strength & conditioning under Stefanski.",
    phase: "draft-week",
  },
  {
    id: "voluntary-minicamp",
    date: "2026-04-21T09:00:00-04:00",
    label: "Voluntary minicamp (new-coach window)",
    detail: "Apr 21–23 at Flowery Branch. One of 10 new-coach teams with a pre-draft voluntary camp. First on-field session under Stefanski.",
    phase: "draft-week",
  },
  {
    id: "draft-r1",
    date: "2026-04-23T20:00:00-04:00",
    label: "NFL Draft — Round 1",
    detail: "Falcons have NO R1 pick. Still required watching for trade-up/trade-down scenarios.",
    phase: "draft-week",
  },
  {
    id: "draft-r2",
    date: "2026-04-24T19:00:00-04:00",
    label: "NFL Draft — Rounds 2-3",
    detail: "Falcons' first pick at #48. Third-round pick at #79.",
    phase: "draft-week",
  },
  {
    id: "draft-r4",
    date: "2026-04-25T12:00:00-04:00",
    label: "NFL Draft — Rounds 4-7",
    detail: "Falcons picks: #122 (R4), #215 (R6), #231 (R7).",
    phase: "draft-week",
  },
  {
    id: "rookie-minicamp-early",
    date: "2026-05-01",
    label: "Rookie Minicamp window opens",
    detail: "League-wide window opens. Atlanta picked the second weekend — six rookies, 16 UDFAs, four tryouts report May 8 to Flowery Branch.",
    phase: "rookie-class",
  },
  {
    id: "rookie-minicamp-falcons",
    date: "2026-05-08",
    label: "Falcons Rookie Minicamp",
    detail: "May 8-10 at Flowery Branch. First on-field reps for Terrell, Branch, Daniels, Thompson, Perkins Jr. and Onianwa plus the UDFA pile.",
    phase: "offseason-lull",
  },
  {
    id: "phase-2-starts",
    date: "2026-05-04",
    label: "Offseason Phase 2 begins",
    detail: "Non-contact walkthroughs + individual drills.",
    phase: "offseason-lull",
  },
  {
    id: "international-slate-release",
    date: "2026-05-13",
    label: "International Slate Released — Falcons host Bengals in Madrid Nov 8",
    detail: "International half of the schedule revealed 9 AM ET on GMFB. Falcons-Bengals locked Sunday Nov 8 (Week 9), 9:30 AM ET at Bernabéu, on NFL Network.",
    phase: "offseason-lull",
  },
  {
    id: "schedule-release",
    date: "2026-05-14",
    label: "2026 NFL Schedule Release (full)",
    detail: "Full calendar drop, 8 PM ET on NFL Network / ESPN2 / NFL+. Bye week, primetime slate, Week 1 opener.",
    phase: "offseason-lull",
  },
  {
    id: "otas-start",
    date: "2026-05-18",
    label: "OTAs begin",
    detail: "Atlanta's official OTA dates: May 18-19, 21, 26-27, 29, June 8-9, 11. Stefanski's first OTA program.",
    phase: "otas-minicamp",
  },
  {
    id: "mandatory-minicamp",
    date: "2026-06-16",
    label: "Mandatory Veteran Minicamp",
    detail: "June 16-18 at Flowery Branch. Attendance required. First look at real competition reps.",
    phase: "otas-minicamp",
  },
  {
    id: "training-camp-open",
    date: "2026-07-22",
    label: "Training Camp opens",
    detail: "Full-team reporting day. Flowery Branch welcomes pads back.",
    phase: "training-camp",
  },
  {
    id: "preseason-wk1",
    date: "2026-08-14",
    label: "Preseason Game 1",
    detail: "First live action of the Stefanski era.",
    phase: "preseason",
  },
  {
    id: "roster-cuts",
    date: "2026-08-26",
    label: "53-man roster cutdown",
    detail: "Teams must reach 53 by 4:00 PM ET.",
    phase: "preseason",
  },
  {
    id: "week-1",
    date: "2026-09-13T13:00:00-04:00",
    label: "Week 1 — Falcons at Pittsburgh",
    detail: "Regular season opens at Pittsburgh, Sun Sep 13, 1 PM ET on FOX. Stefanski era kickoff.",
    phase: "regular-season",
  },
  {
    id: "madrid-game",
    date: "2026-11-08",
    label: "Madrid Game — Falcons HOST Bengals at Bernabéu",
    detail: "Week 9 international. 9:30 AM ET kickoff at Real Madrid's Santiago Bernabéu, on NFL Network. Bijan vs. Burrow/Chase.",
    phase: "regular-season",
  },
];
