// Atlanta Falcons player + team data.
// Hand-curated from live research April 18, 2026. Refreshed by the
// falcons-tracker-update scheduled task.
//
// NOTE on depthRank:
//   1 = starter, 2 = primary backup, 3 = deep reserve, 4 = fringe / practice squad
//
// NOTE on status vocab:
//   active | ir | pup | nfi | suspended | questionable | holdout
//
// Stats are 2025 regular season unless noted. Zero or null where N/A.

export const PLAYERS = [
  // =========================================
  // QUARTERBACKS
  // =========================================
  {
    id: "penix-jr",
    name: "Michael Penix Jr.",
    number: 9,
    position: "QB",
    positionGroup: "offense",
    depthRank: 1,
    height: 75, weight: 216, age: 25, experience: 2,
    college: "Washington",
    acquired: "draft-2024-R1-P8",
    stats: { completions: 166, attempts: 276, passYds: 1982, passTDs: 9, ints: 3, qbRating: 88.5 },
    form: 0,
    status: "pup",
    injuryNote: "ACL rehab · torn Week 11 2025 · expected back for camp",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4360423.png",
    contract: { years: 4, total: 22080000, guaranteed: 22080000, apy: 5520000, throughYear: 2027, cap2026: 5900000 },
    career: [
      { years: "2024–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2023", team: "Washington", type: "College · Heisman finalist" },
    ],
  },
  {
    id: "tua",
    name: "Tua Tagovailoa",
    number: 1,
    position: "QB",
    positionGroup: "offense",
    depthRank: 2,
    height: 73, weight: 227, age: 28, experience: 7,
    college: "Alabama",
    acquired: "fa-2026-1yr",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4241479.png",
    contract: { years: 1, total: 1300000, guaranteed: 1300000, apy: 1300000, throughYear: 2026, cap2026: 1300000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2020–2025", team: "Miami Dolphins", type: "NFL · 2x Pro Bowl" },
      { years: "2017–2019", team: "Alabama", type: "College · 2018 CFP title" },
    ],
  },
  {
    id: "siemian",
    name: "Trevor Siemian",
    number: 13,
    position: "QB",
    positionGroup: "offense",
    depthRank: 3,
    height: 75, weight: 220, age: 34, experience: 10,
    college: "Northwestern",
    acquired: "fa-2026",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/2511109.png",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026, cap2026: 1210000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL · veteran mentor" },
      { years: "2015–2025", team: "Various (DEN, MIN, NYJ, NO, CHI, CIN)", type: "NFL · 33 career starts" },
    ],
  },

  // =========================================
  // RUNNING BACKS
  // =========================================
  {
    id: "bijan",
    name: "Bijan Robinson",
    number: 7,
    position: "RB",
    positionGroup: "offense",
    depthRank: 1,
    height: 71, weight: 215, age: 24, experience: 3,
    college: "Texas",
    acquired: "draft-2023-R1-P8",
    stats: { rushYds: 1478, rushTDs: 14, rushAttempts: 299, receptions: 64, recYds: 820, recTDs: 2, targets: 82 },
    form: 9.2,
    status: "active",
    injuryNote: "5th-year option exercised 4/12 — $11.32M in 2027",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4430807.png",
    contract: { years: 5, total: 33220000, guaranteed: 21900000, apy: 6644000, throughYear: 2027, cap2026: 6820000 },
    career: [
      { years: "2023–", team: "Atlanta Falcons", type: "NFL · 2x Pro Bowl" },
      { years: "2020–2022", team: "Texas", type: "College" },
    ],
  },
  {
    id: "brian-robinson",
    name: "Brian Robinson Jr.",
    number: 24,
    position: "RB",
    positionGroup: "offense",
    depthRank: 2,
    height: 73, weight: 225, age: 27, experience: 5,
    college: "Alabama",
    acquired: "fa-2026-1yr",
    stats: { rushYds: 499, rushTDs: 4, rushAttempts: 125 },
    form: 7.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4241474.png",
    contract: { years: 1, total: 2500000, guaranteed: 1500000, apy: 2500000, throughYear: 2026, cap2026: 2500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Washington Commanders", type: "NFL" },
    ],
  },

  // =========================================
  // WIDE RECEIVERS
  // =========================================
  {
    id: "drake-london",
    name: "Drake London",
    number: 5,
    position: "WR",
    positionGroup: "offense",
    depthRank: 1,
    height: 76, weight: 213, age: 24, experience: 5,
    college: "USC",
    acquired: "draft-2022-R1-P8",
    stats: { receptions: 105, recYds: 1271, recTDs: 9, targets: 145 },
    form: 9.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4426502.png",
    contract: { years: 4, total: 21000000, guaranteed: 15000000, apy: 5250000, throughYear: 2026, cap2026: 16800000 },
    career: [
      { years: "2022–", team: "Atlanta Falcons", type: "NFL · on 5th-year option" },
      { years: "2019–2021", team: "USC", type: "College" },
    ],
  },
  {
    id: "dotson",
    name: "Jahan Dotson",
    number: 1,
    position: "WR",
    positionGroup: "offense",
    depthRank: 2,
    height: 71, weight: 178, age: 26, experience: 5,
    college: "Penn State",
    acquired: "fa-2026-2yr",
    stats: { receptions: 31, recYds: 366, recTDs: 2, targets: 54 },
    form: 6.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4361409.png",
    contract: { years: 2, total: 17000000, guaranteed: 8500000, apy: 8500000, throughYear: 2027, cap2026: 7500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2024–2025", team: "Philadelphia Eagles", type: "NFL · Super Bowl LIX champ" },
      { years: "2022–2023", team: "Washington Commanders", type: "NFL" },
    ],
  },

  // =========================================
  // TIGHT ENDS
  // =========================================
  {
    id: "pitts",
    name: "Kyle Pitts",
    number: 8,
    position: "TE",
    positionGroup: "offense",
    depthRank: 1,
    height: 78, weight: 245, age: 25, experience: 6,
    college: "Florida",
    acquired: "draft-2021-R1-P4",
    stats: { receptions: 58, recYds: 694, recTDs: 4, targets: 92 },
    form: 7.3,
    status: "active",
    injuryNote: "Franchise tagged for 2026 · $14.1M",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4360248.png",
    contract: { years: 1, total: 14124000, guaranteed: 14124000, apy: 14124000, throughYear: 2026, cap2026: 14124000 },
    career: [
      { years: "2021–", team: "Atlanta Falcons", type: "NFL · franchise-tagged" },
      { years: "2018–2020", team: "Florida", type: "College · John Mackey Award" },
    ],
  },
  {
    id: "hooper",
    name: "Austin Hooper",
    number: 81,
    position: "TE",
    positionGroup: "offense",
    depthRank: 2,
    height: 76, weight: 254, age: 31, experience: 10,
    college: "Stanford",
    acquired: "fa-2026",
    stats: { receptions: 26, recYds: 259, recTDs: 3 },
    form: 6.5,
    status: "active",
    injuryNote: "Reunion · Falcons 2016–19, Super Bowl LI roster",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3043275.png",
    contract: { years: 1, total: 3000000, guaranteed: 1500000, apy: 3000000, throughYear: 2026, cap2026: 3000000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2023–2025", team: "New England Patriots", type: "NFL" },
      { years: "2016–2019", team: "Atlanta Falcons", type: "NFL · 2x Pro Bowl" },
    ],
  },
  {
    id: "woerner",
    name: "Charlie Woerner",
    number: 89,
    position: "TE",
    positionGroup: "offense",
    depthRank: 3,
    height: 77, weight: 243, age: 28, experience: 6,
    college: "Georgia",
    acquired: "fa-2024",
    stats: { receptions: 14, recYds: 111, recTDs: 1 },
    form: 6.4,
    status: "active",
    injuryNote: "Potential cut candidate · $4.75M 2026",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4035020.png",
    contract: { years: 3, total: 12000000, guaranteed: 6000000, apy: 4000000, throughYear: 2026, cap2026: 4750000 },
    career: [
      { years: "2024–", team: "Atlanta Falcons", type: "NFL" },
    ],
  },

  // =========================================
  // OFFENSIVE LINE
  // =========================================
  {
    id: "matthews",
    name: "Jake Matthews",
    number: 70,
    position: "OT",
    positionGroup: "offense",
    depthRank: 1,
    height: 77, weight: 309, age: 33, experience: 12,
    college: "Texas A&M",
    acquired: "draft-2014-R1-P6",
    stats: {},
    form: 8.5,
    status: "active",
    injuryNote: "LT · restructured March 2026 (cleared $10.5M)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/16713.png",
    contract: { years: 3, total: 55500000, guaranteed: 0, apy: 18500000, throughYear: 2027, cap2026: 15500000 },
    career: [
      { years: "2014–", team: "Atlanta Falcons", type: "NFL · Pro Bowl 2022" },
    ],
  },
  {
    id: "bergeron",
    name: "Matthew Bergeron",
    number: 65,
    position: "OG",
    positionGroup: "offense",
    depthRank: 1,
    height: 77, weight: 322, age: 25, experience: 3,
    college: "Syracuse",
    acquired: "draft-2023-R2",
    stats: {},
    form: 7.8,
    status: "active",
    injuryNote: "LG · extension candidate",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4568510.png",
    contract: { years: 4, total: 9800000, guaranteed: 5200000, apy: 2450000, throughYear: 2026, cap2026: 2630000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "neuzil",
    name: "Ryan Neuzil",
    number: 66,
    position: "C",
    positionGroup: "offense",
    depthRank: 1,
    height: 75, weight: 297, age: 27, experience: 5,
    college: "Appalachian State",
    acquired: "draft-2021-UDFA",
    stats: {},
    form: 7.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4036444.png",
    contract: { years: 2, total: 7500000, guaranteed: 3750000, apy: 3750000, throughYear: 2026, cap2026: 3750000 },
    career: [{ years: "2021–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "lindstrom",
    name: "Chris Lindstrom",
    number: 63,
    position: "OG",
    positionGroup: "offense",
    depthRank: 1,
    height: 76, weight: 310, age: 29, experience: 7,
    college: "Boston College",
    acquired: "draft-2019-R1-P14",
    stats: {},
    form: 9.3,
    status: "active",
    injuryNote: "RG · 2x All-Pro · restructure candidate",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3672833.png",
    contract: { years: 5, total: 102500000, guaranteed: 55000000, apy: 20500000, throughYear: 2028, cap2026: 19500000 },
    career: [
      { years: "2019–", team: "Atlanta Falcons", type: "NFL · 3x Pro Bowl, 2x All-Pro" },
    ],
  },
  {
    id: "taylor",
    name: "Jawaan Taylor",
    number: 74,
    position: "OT",
    positionGroup: "offense",
    depthRank: 1,
    height: 77, weight: 325, age: 28, experience: 7,
    college: "Florida",
    acquired: "fa-2026",
    stats: {},
    form: 7.5,
    status: "active",
    injuryNote: "RT · ex-Chiefs · signed 4/9 after McGary retirement",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4034961.png",
    contract: { years: 1, total: 5000000, guaranteed: 3000000, apy: 5000000, throughYear: 2026, cap2026: 5000000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL · 1yr/$5M + $1M incentives" },
      { years: "2023–2025", team: "Kansas City Chiefs", type: "NFL · Super Bowl LVIII" },
    ],
  },
  {
    id: "nelson",
    name: "Jack Nelson",
    number: 73,
    position: "OT",
    positionGroup: "offense",
    depthRank: 2,
    height: 79, weight: 315, age: 24, experience: 2,
    college: "Wisconsin",
    acquired: "draft-2025-R7",
    stats: {},
    form: 6.5,
    status: "active",
    injuryNote: "Backup LT",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4693369.png",
    contract: { years: 4, total: 4200000, guaranteed: 100000, apy: 1050000, throughYear: 2028, cap2026: 920000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "hinton",
    name: "Kyle Hinton",
    number: 68,
    position: "OG",
    positionGroup: "offense",
    depthRank: 2,
    height: 74, weight: 302, age: 27, experience: 5,
    college: "Washburn",
    acquired: "fa-2023",
    stats: {},
    form: 6.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4682831.png",
    contract: { years: 2, total: 3500000, guaranteed: 750000, apy: 1750000, throughYear: 2026, cap2026: 1750000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "levin",
    name: "Corey Levin",
    number: 67,
    position: "C",
    positionGroup: "offense",
    depthRank: 2,
    height: 75, weight: 300, age: 30, experience: 7,
    college: "Chattanooga",
    acquired: "fa-2023",
    stats: {},
    form: 6.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/2973637.png",
    contract: { years: 2, total: 3100000, guaranteed: 500000, apy: 1550000, throughYear: 2026, cap2026: 1550000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "stueber",
    name: "Andrew Stueber",
    number: 78,
    position: "OG",
    positionGroup: "offense",
    depthRank: 2,
    height: 79, weight: 325, age: 25, experience: 3,
    college: "Michigan",
    acquired: "fa-2024",
    stats: {},
    form: 6.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4258207.png",
    contract: { years: 1, total: 1200000, guaranteed: 50000, apy: 1200000, throughYear: 2026, cap2026: 1200000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "norton",
    name: "Storm Norton",
    number: 72,
    position: "OT",
    positionGroup: "offense",
    depthRank: 3,
    height: 80, weight: 325, age: 31, experience: 8,
    college: "Toledo",
    acquired: "fa-2024",
    stats: {},
    form: 6.1,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/2973014.png",
    contract: { years: 1, total: 1500000, guaranteed: 200000, apy: 1500000, throughYear: 2026, cap2026: 1500000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // DEFENSIVE LINE
  // =========================================
  {
    id: "dorlus",
    name: "Brandon Dorlus",
    number: 95,
    position: "DT",
    positionGroup: "defense",
    depthRank: 1,
    height: 75, weight: 285, age: 24, experience: 3,
    college: "Oregon",
    acquired: "draft-2024-R4",
    stats: { tackles: 52, solo: 28, tfl: 9, sacks: 8.5, qb_hits: 14 },
    form: 8.4,
    status: "active",
    injuryNote: "Breakout 2025 · 8.5 sacks",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4427090.png",
    contract: { years: 4, total: 4800000, guaranteed: 1900000, apy: 1200000, throughYear: 2027, cap2026: 1100000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "harrison",
    name: "Zach Harrison",
    number: 96,
    position: "DE",
    positionGroup: "defense",
    depthRank: 1,
    height: 78, weight: 272, age: 24, experience: 4,
    college: "Ohio State",
    acquired: "draft-2023-R3",
    stats: { tackles: 41, tfl: 5, sacks: 3.5 },
    form: 7.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4426412.png",
    contract: { years: 4, total: 5400000, guaranteed: 2100000, apy: 1350000, throughYear: 2026, cap2026: 1440000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "maason-smith",
    name: "Maason Smith",
    number: 91,
    position: "DT",
    positionGroup: "defense",
    depthRank: 1,
    height: 77, weight: 306, age: 23, experience: 3,
    college: "LSU",
    acquired: "trade-2026-JAX",
    stats: { tackles: 32, tfl: 3, sacks: 3 },
    form: 6.8,
    status: "active",
    injuryNote: "Acquired 4/17 in DT swap for Ruke Orhorhoro",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4431567.png",
    contract: { years: 4, total: 5900000, guaranteed: 2900000, apy: 1475000, throughYear: 2027, cap2026: 1420000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2024–2025", team: "Jacksonville Jaguars", type: "NFL · 2024 R2 #48" },
    ],
  },
  {
    id: "chris-williams-dl",
    name: "Chris Williams",
    number: 98,
    position: "DT",
    positionGroup: "defense",
    depthRank: 2,
    height: 76, weight: 295, age: 26, experience: 4,
    college: "Wagner",
    acquired: "fa-2026",
    stats: { tackles: 29, sacks: 3.5 },
    form: 6.8,
    status: "active",
    injuryNote: "Ex-Bears · 1-yr deal",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4034530.png",
    contract: { years: 1, total: 2800000, guaranteed: 1500000, apy: 2800000, throughYear: 2026, cap2026: 2800000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Chicago Bears", type: "NFL" },
    ],
  },
  {
    id: "cam-thomas",
    name: "Cameron Thomas",
    number: 55,
    position: "DE",
    positionGroup: "defense",
    depthRank: 2,
    height: 76, weight: 267, age: 26, experience: 5,
    college: "San Diego State",
    acquired: "fa-2026",
    stats: { tackles: 24, sacks: 2 },
    form: 6.4,
    status: "active",
    injuryNote: "Ex-Browns · 1-yr deal",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4361510.png",
    contract: { years: 1, total: 2500000, guaranteed: 1200000, apy: 2500000, throughYear: 2026, cap2026: 2500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Arizona / Cleveland", type: "NFL" },
    ],
  },
  {
    id: "hand",
    name: "Da'Shawn Hand",
    number: 93,
    position: "DT",
    positionGroup: "defense",
    depthRank: 3,
    height: 75, weight: 297, age: 30, experience: 8,
    college: "Alabama",
    acquired: "fa-2026",
    stats: { tackles: 22, tfl: 5 },
    form: 6.5,
    status: "active",
    injuryNote: "Partial replacement for Onyemata · 1-yr / $3M",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3126352.png",
    contract: { years: 1, total: 3000000, guaranteed: 1500000, apy: 3000000, throughYear: 2026, cap2026: 3000000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2024–2025", team: "Los Angeles Chargers", type: "NFL" },
      { years: "2018–2023", team: "Detroit / Tennessee", type: "NFL" },
    ],
  },

  // =========================================
  // EDGE / OLB
  // =========================================
  {
    id: "jalon-walker",
    name: "Jalon Walker",
    number: 45,
    position: "EDGE",
    positionGroup: "defense",
    depthRank: 1,
    height: 74, weight: 245, age: 22, experience: 2,
    college: "Georgia",
    acquired: "draft-2025-R1-P15",
    stats: { tackles: 62, tfl: 10, sacks: 5.5, ff: 1 },
    form: 8.5,
    status: "active",
    injuryNote: "Rookie-year starter · 2024 Butkus Award",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4685597.png",
    contract: { years: 4, total: 19200000, guaranteed: 19200000, apy: 4800000, throughYear: 2028, cap2026: 4400000 },
    career: [
      { years: "2025–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2024", team: "Georgia", type: "College · 2x CFP champ" },
    ],
  },
  {
    id: "pearce-jr",
    name: "James Pearce Jr.",
    number: 27,
    position: "EDGE",
    positionGroup: "defense",
    depthRank: 2,
    height: 77, weight: 245, age: 22, experience: 2,
    college: "Tennessee",
    acquired: "draft-2025-R1-P26",
    stats: { tackles: 31, sacks: 4.5 },
    form: 7.6,
    status: "active",
    injuryNote: "Rookie contributor · high-upside",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/5081394.png",
    contract: { years: 4, total: 14500000, guaranteed: 14500000, apy: 3625000, throughYear: 2028, cap2026: 3350000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "ojulari",
    name: "Azeez Ojulari",
    number: 51,
    position: "EDGE",
    positionGroup: "defense",
    depthRank: 2,
    height: 74, weight: 240, age: 26, experience: 6,
    college: "Georgia",
    acquired: "fa-2026-1yr",
    stats: { tackles: 28, sacks: 6, ff: 1 },
    form: 7.3,
    status: "active",
    injuryNote: "Ex-Giants · homecoming (UGA)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4379409.png",
    contract: { years: 1, total: 4000000, guaranteed: 2500000, apy: 4000000, throughYear: 2026, cap2026: 4000000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2021–2025", team: "New York Giants", type: "NFL" },
    ],
  },

  // =========================================
  // LINEBACKERS
  // =========================================
  {
    id: "christian-harris",
    name: "Christian Harris",
    number: 48,
    position: "LB",
    positionGroup: "defense",
    depthRank: 1,
    height: 73, weight: 230, age: 25, experience: 5,
    college: "Alabama",
    acquired: "trade-2025",
    stats: { tackles: 74, tfl: 6, sacks: 1.5 },
    form: 7.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4567099.png",
    contract: { years: 1, total: 3300000, guaranteed: 3300000, apy: 3300000, throughYear: 2026, cap2026: 3300000 },
    career: [
      { years: "2025–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2024", team: "Houston Texans", type: "NFL" },
    ],
  },
  {
    id: "andersen",
    name: "Troy Andersen",
    number: 44,
    position: "LB",
    positionGroup: "defense",
    depthRank: 2,
    height: 75, weight: 243, age: 26, experience: 5,
    college: "Montana State",
    acquired: "draft-2022-R2",
    stats: { tackles: 31 },
    form: 6.6,
    status: "questionable",
    injuryNote: "Shoulder recovery from 2025 IR stint",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4247807.png",
    contract: { years: 1, total: 3420000, guaranteed: 3420000, apy: 3420000, throughYear: 2026, cap2026: 3420000 },
    career: [{ years: "2022–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "tindall",
    name: "Channing Tindall",
    number: 47,
    position: "LB",
    positionGroup: "defense",
    depthRank: 2,
    height: 74, weight: 230, age: 26, experience: 5,
    college: "Georgia",
    acquired: "fa-2026",
    stats: { tackles: 42 },
    form: 6.6,
    status: "active",
    injuryNote: "Ex-Cardinals · another UGA addition",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4379414.png",
    contract: { years: 1, total: 1800000, guaranteed: 500000, apy: 1800000, throughYear: 2026, cap2026: 1800000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Miami / Arizona", type: "NFL" },
    ],
  },

  // =========================================
  // CORNERBACKS
  // =========================================
  {
    id: "terrell",
    name: "A.J. Terrell",
    number: 24,
    position: "CB",
    positionGroup: "defense",
    depthRank: 1,
    height: 73, weight: 195, age: 27, experience: 7,
    college: "Clemson",
    acquired: "draft-2020-R1-P16",
    stats: { tackles: 68, int_def: 2, pass_def: 13 },
    form: 8.2,
    status: "active",
    injuryNote: "CB1 · paid like one (4yr/$81M extension in 2024)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4239995.png",
    contract: { years: 4, total: 81000000, guaranteed: 43500000, apy: 20250000, throughYear: 2028, cap2026: 19200000 },
    career: [{ years: "2020–", team: "Atlanta Falcons", type: "NFL · Pro Bowl 2021" }],
  },
  {
    id: "hughes",
    name: "Mike Hughes",
    number: 21,
    position: "CB",
    positionGroup: "defense",
    depthRank: 1,
    height: 70, weight: 190, age: 29, experience: 8,
    college: "UCF",
    acquired: "fa-2023",
    stats: { tackles: 57, int_def: 1, pass_def: 8 },
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3895841.png",
    contract: { years: 2, total: 9000000, guaranteed: 3000000, apy: 4500000, throughYear: 2026, cap2026: 4200000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "brooks-cb",
    name: "Natrone Brooks",
    number: 39,
    position: "CB",
    positionGroup: "defense",
    depthRank: 2,
    height: 71, weight: 190, age: 27, experience: 4,
    college: "Mississippi Valley State",
    acquired: "extension-2026",
    stats: { tackles: 32, pass_def: 4 },
    form: 6.8,
    status: "active",
    injuryNote: "Extended March 2026",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4689989.png",
    contract: { years: 2, total: 4500000, guaranteed: 2000000, apy: 2250000, throughYear: 2027, cap2026: 2250000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "phillips-cb",
    name: "Clark Phillips III",
    number: 23,
    position: "CB",
    positionGroup: "defense",
    depthRank: 3,
    height: 70, weight: 184, age: 24, experience: 4,
    college: "Utah",
    acquired: "draft-2023-R4",
    stats: { tackles: 28, int_def: 2, pass_def: 4 },
    form: 6.7,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4429067.png",
    contract: { years: 4, total: 4800000, guaranteed: 1600000, apy: 1200000, throughYear: 2026, cap2026: 1250000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // SAFETIES
  // =========================================
  {
    id: "bates",
    name: "Jessie Bates III",
    number: 3,
    position: "S",
    positionGroup: "defense",
    depthRank: 1,
    height: 74, weight: 200, age: 29, experience: 9,
    college: "Wake Forest",
    acquired: "fa-2024",
    stats: { tackles: 98, int_def: 3, pass_def: 9, ff: 1 },
    form: 9.1,
    status: "active",
    injuryNote: "All-Pro · restructure candidate",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3919512.png",
    contract: { years: 4, total: 64000000, guaranteed: 36000000, apy: 16000000, throughYear: 2027, cap2026: 16800000 },
    career: [
      { years: "2024–", team: "Atlanta Falcons", type: "NFL · All-Pro 2024" },
      { years: "2018–2023", team: "Cincinnati Bengals", type: "NFL · Super Bowl LVI" },
    ],
  },
  {
    id: "xavier-watts",
    name: "Xavier Watts",
    number: 32,
    position: "S",
    positionGroup: "defense",
    depthRank: 1,
    height: 72, weight: 205, age: 23, experience: 2,
    college: "Notre Dame",
    acquired: "draft-2025-R3",
    stats: { tackles: 58, int_def: 4, pass_def: 6 },
    form: 8.2,
    status: "active",
    injuryNote: "Rookie-year impact · ballhawk",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4431005.png",
    contract: { years: 4, total: 5100000, guaranteed: 4600000, apy: 1275000, throughYear: 2028, cap2026: 1170000 },
    career: [
      { years: "2025–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2021–2024", team: "Notre Dame", type: "College · 2x Bronko Nagurski winner" },
    ],
  },
  {
    id: "sydney-brown",
    name: "Sydney Brown",
    number: 30,
    position: "S",
    positionGroup: "defense",
    depthRank: 2,
    height: 70, weight: 205, age: 26, experience: 4,
    college: "Illinois",
    acquired: "trade-2026-PHI",
    stats: { tackles: 41, int_def: 1, pass_def: 3 },
    form: 7.0,
    status: "active",
    injuryNote: "Acquired Mar 20 from Philly in pick swap",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4360386.png",
    contract: { years: 1, total: 1400000, guaranteed: 200000, apy: 1400000, throughYear: 2026, cap2026: 1400000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2023–2025", team: "Philadelphia Eagles", type: "NFL · Super Bowl LIX champ" },
    ],
  },
  {
    id: "hellams",
    name: "DeMarcco Hellams",
    number: 28,
    position: "S",
    positionGroup: "defense",
    depthRank: 3,
    height: 72, weight: 205, age: 25, experience: 4,
    college: "Alabama",
    acquired: "draft-2023-R7",
    stats: { tackles: 36 },
    form: 6.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4567111.png",
    contract: { years: 4, total: 3800000, guaranteed: 200000, apy: 950000, throughYear: 2026, cap2026: 1100000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // 2026 DRAFT CLASS — rookies report May 1 / 8 for minicamp
  // =========================================
  {
    id: "avieon-terrell",
    name: "Avieon Terrell",
    number: null,
    position: "CB",
    positionGroup: "defense",
    depthRank: 2,
    height: 71, weight: 184, age: 21, experience: 0,
    college: "Clemson",
    acquired: "draft-2026-R2-P48",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Hamstring re-aggravation at private pro day; expected fully cleared by minicamp",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4870988.png",
    contract: { years: 4, total: 8500000, guaranteed: 4200000, apy: 2125000, throughYear: 2029, cap2026: 1400000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL · 1st known starting-CB sibling tandem" },
      { years: "2022–2025", team: "Clemson", type: "College · A.J. Terrell's brother" },
    ],
  },
  {
    id: "zachariah-branch",
    name: "Zachariah Branch",
    number: null,
    position: "WR",
    positionGroup: "offense",
    depthRank: 3,
    height: 69, weight: 178, age: 21, experience: 0,
    college: "Georgia",
    acquired: "draft-2026-R3-P79",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4870612.png",
    contract: { years: 4, total: 5800000, guaranteed: 1850000, apy: 1450000, throughYear: 2029, cap2026: 1100000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2025", team: "Georgia", type: "College · transfer from USC" },
      { years: "2023–2024", team: "USC", type: "College · 2023 Jet Award winner" },
    ],
  },
  {
    id: "kendal-daniels",
    name: "Kendal Daniels",
    number: null,
    position: "LB",
    positionGroup: "defense",
    depthRank: 3,
    height: 76, weight: 222, age: 23, experience: 0,
    college: "Oklahoma",
    acquired: "draft-2026-R4-P134",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4595343.png",
    contract: { years: 4, total: 4750000, guaranteed: 700000, apy: 1187500, throughYear: 2029, cap2026: 900000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2025", team: "Oklahoma", type: "College · 'Cheetah' hybrid LB · 13 GS, 9 TFL" },
      { years: "2022–2024", team: "Oklahoma State", type: "College · safety" },
    ],
  },
  {
    id: "anterio-thompson",
    name: "Anterio Thompson",
    number: null,
    position: "DT",
    positionGroup: "defense",
    depthRank: 4,
    height: 74, weight: 306, age: 23, experience: 0,
    college: "Washington",
    acquired: "draft-2026-R6-P208",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/5150660.png",
    contract: { years: 4, total: 4250000, guaranteed: 130000, apy: 1062500, throughYear: 2029, cap2026: 850000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2021–2025", team: "Washington", type: "College · 4.73 forty / 3 blocked punts in 2025" },
    ],
  },
  {
    id: "harold-perkins",
    name: "Harold Perkins Jr.",
    number: null,
    position: "LB",
    positionGroup: "defense",
    depthRank: 4,
    height: 73, weight: 220, age: 22, experience: 0,
    college: "LSU",
    acquired: "draft-2026-R6-P215",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Returning from torn right ACL (2024); ran 4.45 at pro day",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4685502.png",
    contract: { years: 4, total: 4450000, guaranteed: 100000, apy: 1112500, throughYear: 2029, cap2026: 850000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "LSU", type: "College · 2022 Freshman All-American" },
    ],
  },
  {
    id: "ethan-onianwa",
    name: "Ethan Onianwa",
    number: null,
    position: "OT",
    positionGroup: "offense",
    depthRank: 4,
    height: 78, weight: 333, age: 23, experience: 0,
    college: "Ohio State",
    acquired: "draft-2026-R7-P231",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4683194.png",
    contract: { years: 4, total: 4150000, guaranteed: 80000, apy: 1037500, throughYear: 2029, cap2026: 800000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2025", team: "Ohio State", type: "College · transfer · did not start" },
      { years: "2021–2024", team: "Rice", type: "College · 34 starts at OT" },
    ],
  },

  // =========================================
  // SPECIAL TEAMS
  // =========================================
  {
    id: "folk",
    name: "Nick Folk",
    number: 6,
    position: "K",
    positionGroup: "special",
    depthRank: 1,
    height: 73, weight: 222, age: 41, experience: 19,
    college: "Arizona",
    acquired: "fa-2026",
    stats: { fgMade: 31, fgAttempted: 35, longFG: 55, xpMade: 28, xpAttempted: 29 },
    form: 8.8,
    status: "active",
    injuryNote: "Ageless · 88.6% career FG",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/10621.png",
    contract: { years: 2, total: 5000000, guaranteed: 2000000, apy: 2500000, throughYear: 2027, cap2026: 2500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2007–2025", team: "Dallas / Tampa / NY Jets / New England / Tennessee", type: "NFL · Pro Bowl 2023" },
    ],
  },
  {
    id: "bailey",
    name: "Jake Bailey",
    number: 7,
    position: "P",
    positionGroup: "special",
    depthRank: 1,
    height: 74, weight: 208, age: 28, experience: 7,
    college: "Stanford",
    acquired: "fa-2026-3yr",
    stats: { puntAvg: 48.2, netPuntAvg: 42.8, punts_i20: 25 },
    form: 8.4,
    status: "active",
    injuryNote: "1x All-Pro (2020)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3931395.png",
    contract: { years: 3, total: 9000000, guaranteed: 4000000, apy: 3000000, throughYear: 2028, cap2026: 2800000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2019–2025", team: "New England / Miami", type: "NFL · 2020 All-Pro" },
    ],
  },
  {
    id: "mccullough-ls",
    name: "Liam McCullough",
    number: 48,
    position: "LS",
    positionGroup: "special",
    depthRank: 1,
    height: 74, weight: 230, age: 28, experience: 5,
    college: "Ohio State",
    acquired: "fa-2022",
    stats: {},
    form: 7.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3915528.png",
    contract: { years: 2, total: 2700000, guaranteed: 500000, apy: 1350000, throughYear: 2026, cap2026: 1400000 },
    career: [{ years: "2022–", team: "Atlanta Falcons", type: "NFL" }],
  },
];

// =========================================
// TEAM LOGOS
// =========================================
export const TEAM_LOGOS = {
  ATL: "https://static.www.nfl.com/image/private/f_auto/league/d8m7hzpsbrl6pnqht8op",
  NO: "https://static.www.nfl.com/image/private/f_auto/league/grhjkahghjkk17v43hdx",
  CAR: "https://static.www.nfl.com/image/private/f_auto/league/ervfzgrqdpnc7lh5gqwq",
  TB: "https://static.www.nfl.com/image/private/f_auto/league/v8uqiualryypwqgvwcih",
  PHI: "https://static.www.nfl.com/image/private/f_auto/league/puhrqgj71gobgdkdo6uq",
  KC: "https://static.www.nfl.com/image/private/f_auto/league/ujshjqvmnxce8m4obmvs",
  SF: "https://static.www.nfl.com/image/private/f_auto/league/dxibuyxbk0b9ua5ih9hn",
  WAS: "https://static.www.nfl.com/image/private/f_auto/league/xymxwrl1zp4xzcfsbvuf",
  DET: "https://static.www.nfl.com/image/private/f_auto/league/ocvxwnapdvwevupe4tpr",
  GB: "https://static.www.nfl.com/image/private/f_auto/league/gppfvr7n8gljgjaqux2x",
  CHI: "https://static.www.nfl.com/image/private/f_auto/league/ra0poq2ivwyahbaq86d2",
  MIN: "https://static.www.nfl.com/image/private/f_auto/league/teguylrnqqmfcwxvcmmz",
  PIT: "https://static.www.nfl.com/image/private/f_auto/league/xujg9t3t4u5nmjgr54wx",
  BAL: "https://static.www.nfl.com/image/private/f_auto/league/ucsdijmddsqcj1i9tddd",
  CIN: "https://static.www.nfl.com/image/private/f_auto/league/okxpteoliyayufypqalq",
  CLE: "https://static.www.nfl.com/image/private/f_auto/league/fgbn8acp4opvyxk13dcy",
};

// =========================================
// RSS FEEDS
// =========================================
export const RSS_FEEDS = [
  {
    name: "The Falcoholic",
    url: "https://www.thefalcoholic.com/rss/index.xml",
    color: "#A71930",
  },
  {
    name: "ESPN NFL",
    url: "https://www.espn.com/espn/rss/nfl/news",
    color: "#de0613",
  },
  {
    name: "Pro Football Rumors · Falcons",
    url: "https://www.profootballrumors.com/atlanta-falcons/feed",
    color: "#F39C12",
  },
];

// =========================================
// NEXT GAME (null during offseason)
// =========================================
export const NEXT_GAME = null;

// =========================================
// 2025 SEASON RECAP
// =========================================
export const SEASON_RECAP_2025 = {
  record: "8-9",
  divisionFinish: "3rd NFC South",
  playoffsResult: "Missed · 7th straight",
  pointsFor: 378,
  pointsAgainst: 392,
  netDifferential: -14,
  storylines: [
    "Started 4-9 before winning final four games",
    "Michael Penix Jr. took over as QB1 midseason",
    "Penix tore ACL Week 11 vs Seahawks (season-ending)",
    "Fired HC Raheem Morris + GM Terry Fontenot after Week 18",
    "Kevin Stefanski + Ian Cunningham hired to lead reset",
  ],
  keyStats: {
    bijanRushYds: 1478,
    bijanTDs: 14,
    londonRecYds: 1271,
    batesTackles: 98,
    batesInts: 3,
    walkerSacks: 5.5,
    dorlusSacks: 8.5,
  },
};

// =========================================
// RESULTS 2025 — final full season
// =========================================
export const RESULTS_2025 = [
  { date: "2025-09-07", opp: "TB", home: false, atlScore: 17, oppScore: 22, result: "L" },
  { date: "2025-09-14", opp: "PHI", home: true, atlScore: 22, oppScore: 21, result: "W" },
  { date: "2025-09-21", opp: "KC", home: false, atlScore: 17, oppScore: 22, result: "L" },
  { date: "2025-09-28", opp: "NO", home: true, atlScore: 26, oppScore: 24, result: "W" },
  { date: "2025-10-05", opp: "WAS", home: true, atlScore: 20, oppScore: 27, result: "L" },
  { date: "2025-10-12", opp: "BUF", home: false, atlScore: 17, oppScore: 34, result: "L" },
  { date: "2025-10-19", opp: "SF", home: true, atlScore: 20, oppScore: 17, result: "W" },
  { date: "2025-10-26", opp: "TB", home: true, atlScore: 24, oppScore: 27, result: "L" },
  { date: "2025-11-10", opp: "NO", home: false, atlScore: 21, oppScore: 24, result: "L" },
  { date: "2025-11-17", opp: "DEN", home: true, atlScore: 13, oppScore: 20, result: "L" },
  { date: "2025-11-24", opp: "SEA", home: false, atlScore: 10, oppScore: 27, result: "L" },
  { date: "2025-12-01", opp: "LAC", home: true, atlScore: 17, oppScore: 23, result: "L" },
  { date: "2025-12-08", opp: "MIN", home: false, atlScore: 14, oppScore: 28, result: "L" },
  { date: "2025-12-14", opp: "LV", home: true, atlScore: 31, oppScore: 17, result: "W" },
  { date: "2025-12-21", opp: "ARI", home: false, atlScore: 28, oppScore: 21, result: "W" },
  { date: "2025-12-28", opp: "CAR", home: true, atlScore: 34, oppScore: 13, result: "W" },
  { date: "2026-01-04", opp: "NO", home: false, atlScore: 27, oppScore: 24, result: "W" },
];

// =========================================
// NFC SOUTH 2025 FINAL STANDINGS
// =========================================
export const NFC_SOUTH_STANDINGS_2025 = [
  { team: "Tampa Bay Buccaneers", code: "TB", wins: 11, losses: 6, pct: 0.647, divisionFinish: 1 },
  { team: "New Orleans Saints", code: "NO", wins: 9, losses: 8, pct: 0.529, divisionFinish: 2 },
  { team: "Atlanta Falcons", code: "ATL", wins: 8, losses: 9, pct: 0.471, divisionFinish: 3, isFalcons: true },
  { team: "Carolina Panthers", code: "CAR", wins: 5, losses: 12, pct: 0.294, divisionFinish: 4 },
];

// =========================================
// NEWS DIGEST — refreshed daily by scheduled task
// =========================================
export const NEWS_DIGEST = {
  generatedAt: "2026-04-29T18:30:00Z",
  sources: [
    "Atlanta Falcons Official", "ESPN", "NFL.com", "The Falcoholic",
    "Bleacher Report", "Pro Football Rumors", "SI Falcons", "NBC Sports",
    "Yahoo Sports", "Spotrac", "Heavy.com", "CBS Sports", "AJC",
    "The Athletic", "Pro Football Network", "FBSchedules", "BloggingDirty",
    "Saturday Down South", "Pro Football Talk", "Yardbarker", "PFF",
    "Locked On Atlanta", "FanSided", "ClutchPoints", "TWSN", "Over The Cap",
    "National Today", "Freedom 96.9", "Athlon Sports", "Audacy 92.9 The Game",
    "Kicks 99", "BetMGM", "Wikipedia",
  ],
  topics: [
    {
      title: "Schefter raising eyebrows: Pitts trade chatter persists despite signed franchise tag",
      detail: "Wednesday's biggest local rumor wave: ClutchPoints, Yahoo and Heavy all flagged that Adam Schefter has now mentioned a Kyle Pitts trade multiple times since the draft closed. Cunningham reportedly remains 'willing to listen' even after Pitts signed the $15.045M tag and showed for voluntary workouts. The trigger is acknowledged in print — Atlanta's draft-capital crunch from the Pearce Jr. trade-up plus a possible R1 conduct-policy suspension on Pearce makes a tag-and-trade more rationalizable than it looked two weeks ago. Heavy floated a Chiefs-as-Kelce-successor scenario as the cleanest fit.",
      category: "contracts",
    },
    {
      title: "Pearce Jr. legal path: charges drop if pretrial diversion completes — but NFL 6-game suspension still on the table",
      detail: "PFR/PFT/Falcoholic confirmed Apr 23–28 that Pearce Jr.'s multiple felony charges (battery, stalking, fleeing) plus traffic citations will be dismissed if he completes a Florida pretrial diversion program — therapy plus six clean months, no admission of guilt, with the program landing in Week 7 of the NFL season. The legal track is the easy part: NFL discipline does not require a conviction, and the personal-conduct-policy floor for a first offense is a six-game suspension. Cunningham has not commented publicly; the team is bracing for a partial-season Pearce.",
      category: "general",
    },
    {
      title: "Home/away matchups OFFICIAL — schedule release moved up to May 12–14 window",
      detail: "Falcons.com and BetMGM/Falcoholic posted the finalized matchup list this week. HOME (9): Carolina, New Orleans, Tampa Bay, Baltimore, Chicago, Cincinnati, Detroit, Kansas City, San Francisco. AWAY (8): Carolina, New Orleans, Tampa Bay, Cleveland, Green Bay, Minnesota, Pittsburgh, Washington. KC's appearance as a home opponent makes the Mahomes-at-Bernabéu Madrid scenario suddenly clean — Atlanta is the designated home team. Dates and primetime slot count are still gated on the May 12–14 release.",
      category: "general",
    },
    {
      title: "Rookie minicamp roster locked: 6 picks + 16 UDFAs + tryout invites report to Flowery Branch May 8–11",
      detail: "Atlanta announced the official rookie-camp roster this week. Six drafted rookies plus a 16-UDFA class — DT Carlos Allen (Houston, FBS-leading 80 tackles among interior DLs), C James Brockermeyer (Miami, All-ACC 3rd team / Senior Bowl), QB Jack Strand (Minnesota-Moorhead), OT Riley Mahlman (Wisconsin), WR Vinny Anthony II (Wisconsin), CB Malcolm DeWalt IV (Akron), G Kam Dewberry (Alabama), TEs Frazier/Velling, returner Keelan Marion and more — headline the field group. First on-field reps of the Stefanski / Rees / Ulbrich install for the rookie set.",
      category: "general",
    },
    {
      title: "Avieon arrives in Flowery Branch — 'first known starting-CB sibling tandem' photo set drops",
      detail: "atlantafalcons.com published the Avieon-Terrell-arrives photo gallery and a sit-down with both Terrells this week. A.J.: 'I had to wait three picks before I could even show some type of love to him.' Avieon stays at No. 12 (his Clemson number was 4); A.J. keeps 24. The team is openly leaning into the brothers angle as the marketing centerpiece of the rookie class.",
      category: "general",
    },
    {
      title: "Rookie jersey numbers revealed: Branch No. 17, Avieon Terrell No. 12, Perkins Jr. No. 56",
      detail: "Tuesday's number drop from atlantafalcons.com. CB Avieon Terrell — No. 12; WR Zachariah Branch — No. 17; LB Kendal Daniels — No. 53; LB Harold Perkins Jr. — No. 56; OT Ethan Onianwa — No. 75; DT Anterio Thompson — No. 98. None of the six carries his college number. First on-field reps in those jerseys come at the May 8–11 rookie minicamp.",
      category: "general",
    },
    {
      title: "Drake London extension still 'top of mind' — JSN's $42.15M APY is the new ceiling Cunningham must respect",
      detail: "Cunningham's post-draft Saturday line that London is 'top of mind' is now the most-cited offseason quote in town. London plays 2026 on the $16.8M 5th-year option. The market keeps moving: Jaxon Smith-Njigba's 4yr / $168.6M ($42.15M APY) deal reset the WR ceiling; Garrett Wilson's $131M Jets number is the floor for top-15 production. Heavy / TWSN / SI projections cluster at 4yr / $128M ($32M APY, $82–90M gtd). Stated org goal: lock it before camp opens July 22.",
      category: "contracts",
    },
    {
      title: "Bijan extension queue is open — Gibbs/Detroit timing remains the chief market-reset risk",
      detail: "B/R and Yardbarker confirmed Cunningham said extensions for Bijan and London 'won't come until after the draft,' which is now. Bijan's 5th-year option was exercised Apr 10–13 at $11.32M for 2027. ESPN's contract-prediction piece pegs $20M+ APY; the open question is whether Detroit closes Jahmyr Gibbs first — same negotiating window, identical resumes. Bijan's 2025 case (1,478 rushing, 820 receiving, 16 total TDs, All-Pro) is at least Gibbs-equal on tape.",
      category: "contracts",
    },
    {
      title: "Penix ACL update: Stefanski holds 'right where he needs to be,' Tua-vs-Penix QB battle frame stays open",
      detail: "PFN, NBC PFT and SI all ran Stefanski's most recent rehab line this week — 'right where he needs to be' on Penix's Nov 16 ACL tear (surgery Nov 25). Penix continues to target a Week 1 return; AJC reports him back at the facility, mentally locked in, physically clean. Tua's 1yr / $1.3M bridge deal preserves the QB1 option, and Stefanski's mantra to both QBs at voluntary minicamp Apr 21–23 was 'be where your feet are.'",
      category: "injuries",
    },
    {
      title: "Class grades land B- to B+: Day 2 universally praised, Day 3 LB double-dip is the lightning rod",
      detail: "Final report cards converged Mon–Tue: NFL.com's Chad Reuter at B- (penalty for the 2026 R1 traded for Pearce Jr. + zero edge picks); CBS's Carter Bahns at B+ (no penalty for the no-R1 reality); ESPN A/A- on Day 2 (Terrell at #48, Branch at #79). Day 3 split the rooms — Kiper and PFN praised the Daniels/Perkins LB pairing as Cheetah-and-Star types; Edwards called Daniels 'a player without a position.' Consensus: solid B / B+ given the starting point.",
      category: "draft",
    },
    {
      title: "Phase 2 walkthroughs open Monday May 4 — first on-field reps for the veteran offense under Stefanski-Rees",
      detail: "Per the NFL Football Operations release and Falcons.com, Atlanta's offseason program is in Phase 1 strength/conditioning now and rotates into Phase 2 walkthroughs on May 4 — the first window where the full veteran skill group gets on-field installation reps with no contact. Phase 3 OTAs (May 18–19 / 21 / 26–27 / 29 / June 8–9 / 11) follow; mandatory veteran minicamp June 16–18 closes the program before camp opens July 22.",
      category: "coaching",
    },
    {
      title: "UDFA OL pile is the sleeper story — Bill Callahan inherits real developmental depth at G/C/T",
      detail: "Falcoholic / SI / NFL.com cross-checks confirm Atlanta signed multiple offensive linemen as UDFAs: C James Brockermeyer (Miami, All-ACC 3rd team, Senior Bowl), G Kam Dewberry (Alabama LG starter), OT Riley Mahlman (Wisconsin), plus pass-catching depth via TEs Velling/Frazier. With Lindstrom/Matthews locked in and Taylor on a 1yr / $5M McGary-replacement deal, the UDFA group is genuine swing-tackle and interior depth competition under new OL coach Bill Callahan.",
      category: "draft",
    },
    {
      title: "DT room post-draft: Smith + Harrison + Dorlus + rookie Thompson + UDFA Allen — finally back to full numbers",
      detail: "The Apr 17 player-for-player swap with Jacksonville sent Ruke Orhorhoro out and brought Maason Smith in. The Apr 25–26 draft added 6th-rounder Anterio Thompson at #208 (4.73 forty at 306, 3 blocked punts). The priority UDFA signing of Houston's Carlos Allen (FBS-leading 80 tackles among interior DLs in 2025) rounds out the interior: Smith (NT), Harrison (3-tech), Dorlus (rotation), Thompson (developmental), Allen (camp-stay flier). Reduced from the Onyemata era — not eliminated.",
      category: "free-agency",
    },
    {
      title: "Calendar in motion: Phase 2 May 4 → rookie camp May 8–11 → schedule release May 12–14 → OTAs May 18",
      detail: "Five days from the next milestone. Phase 2 walkthroughs open Monday May 4; rookie minicamp at Flowery Branch May 8–11 (the second of two NFL-allowed post-draft windows); 2026 NFL schedule release tracking to the May 12–14 window; Phase 3 OTAs begin May 18. Then mandatory veteran minicamp June 16–18, dead period through July 21, training camp opens July 22 in Flowery Branch. The dashboard hero rotates out of 'rookie-class' on May 5.",
      category: "general",
    },
  ],
};
