// Atlanta Falcons player + team data.
// Hand-curated from live research April 18, 2026. Refreshed by the
// falcons-tracker-update scheduled task.
//
// NOTE on depthRank:
//   1 = starter, 2 = primary backup, 3 = deep reserve, 4 = fringe / practice squad
//
// NOTE on status vocab:
//   active | ir | pup | nfi | suspended | questionable | holdout
//
// Stats are 2025 regular season unless noted. Zero or null where N/A.

export const PLAYERS = [
  // =========================================
  // QUARTERBACKS
  // =========================================
  {
    id: "penix-jr",
    name: "Michael Penix Jr.",
    number: 9,
    position: "QB",
    positionGroup: "offense",
    depthRank: 1,
    height: 75, weight: 216, age: 25, experience: 2,
    college: "Washington",
    acquired: "draft-2024-R1-P8",
    stats: { completions: 166, attempts: 276, passYds: 1982, passTDs: 9, ints: 3, qbRating: 88.5 },
    form: 0,
    status: "pup",
    injuryNote: "ACL rehab · torn Week 11 2025 · expected back for camp",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4360423.png",
    contract: { years: 4, total: 22080000, guaranteed: 22080000, apy: 5520000, throughYear: 2027, cap2026: 5900000 },
    career: [
      { years: "2024–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2023", team: "Washington", type: "College · Heisman finalist" },
    ],
  },
  {
    id: "tua",
    name: "Tua Tagovailoa",
    number: 1,
    position: "QB",
    positionGroup: "offense",
    depthRank: 2,
    height: 73, weight: 227, age: 28, experience: 7,
    college: "Alabama",
    acquired: "fa-2026-1yr",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4241479.png",
    contract: { years: 1, total: 1300000, guaranteed: 1300000, apy: 1300000, throughYear: 2026, cap2026: 1300000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2020–2025", team: "Miami Dolphins", type: "NFL · 2x Pro Bowl" },
      { years: "2017–2019", team: "Alabama", type: "College · 2018 CFP title" },
    ],
  },
  {
    id: "siemian",
    name: "Trevor Siemian",
    number: 13,
    position: "QB",
    positionGroup: "offense",
    depthRank: 3,
    height: 75, weight: 220, age: 34, experience: 10,
    college: "Northwestern",
    acquired: "fa-2026",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/2511109.png",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026, cap2026: 1210000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL · veteran mentor" },
      { years: "2015–2025", team: "Various (DEN, MIN, NYJ, NO, CHI, CIN)", type: "NFL · 33 career starts" },
    ],
  },

  // =========================================
  // RUNNING BACKS
  // =========================================
  {
    id: "bijan",
    name: "Bijan Robinson",
    number: 7,
    position: "RB",
    positionGroup: "offense",
    depthRank: 1,
    height: 71, weight: 215, age: 24, experience: 3,
    college: "Texas",
    acquired: "draft-2023-R1-P8",
    stats: { rushYds: 1478, rushTDs: 14, rushAttempts: 299, receptions: 64, recYds: 820, recTDs: 2, targets: 82 },
    form: 9.2,
    status: "active",
    injuryNote: "5th-year option exercised 4/12 — $11.32M in 2027",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4430807.png",
    contract: { years: 5, total: 33220000, guaranteed: 21900000, apy: 6644000, throughYear: 2027, cap2026: 6820000 },
    career: [
      { years: "2023–", team: "Atlanta Falcons", type: "NFL · 2x Pro Bowl" },
      { years: "2020–2022", team: "Texas", type: "College" },
    ],
  },
  {
    id: "brian-robinson",
    name: "Brian Robinson Jr.",
    number: 15,
    position: "RB",
    positionGroup: "offense",
    depthRank: 2,
    height: 73, weight: 225, age: 27, experience: 5,
    college: "Alabama",
    acquired: "fa-2026-1yr",
    stats: { rushYds: 499, rushTDs: 4, rushAttempts: 125 },
    form: 7.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4241474.png",
    contract: { years: 1, total: 2500000, guaranteed: 1500000, apy: 2500000, throughYear: 2026, cap2026: 2500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Washington Commanders", type: "NFL" },
    ],
  },
  {
    id: "goodson",
    name: "Tyler Goodson",
    number: 25,
    position: "RB",
    positionGroup: "offense",
    depthRank: 3,
    height: 70, weight: 200, age: 25, experience: 4,
    college: "Iowa",
    acquired: "fa-2026",
    stats: {},
    form: 6.4,
    status: "active",
    injuryNote: "Change-of-pace + 3rd-down back · ex-Colts",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4429676.png",
    contract: { years: 1, total: 1300000, guaranteed: 200000, apy: 1300000, throughYear: 2026, cap2026: 1300000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Indianapolis Colts", type: "NFL" },
    ],
  },
  {
    id: "nathan-carter",
    name: "Nathan Carter",
    number: 38,
    position: "RB",
        stRoles: ["KR"],
    stRank: {"KR":3},
    positionGroup: "offense",
    depthRank: 4,
    height: 71, weight: 200, age: 23, experience: 2,
    college: "Michigan State",
    acquired: "fa-2025-UDFA",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Camp / PS bubble",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4605841.png",
    contract: { years: 1, total: 960000, guaranteed: 0, apy: 960000, throughYear: 2026, cap2026: 960000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // WIDE RECEIVERS
  // =========================================
  {
    id: "drake-london",
    name: "Drake London",
    number: 5,
    position: "WR",
    posSlot: "X",
    positionGroup: "offense",
    depthRank: 1,
    height: 76, weight: 213, age: 24, experience: 5,
    college: "USC",
    acquired: "draft-2022-R1-P8",
    stats: { receptions: 105, recYds: 1271, recTDs: 9, targets: 145 },
    form: 9.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4426502.png",
    contract: { years: 4, total: 21000000, guaranteed: 15000000, apy: 5250000, throughYear: 2026, cap2026: 16800000 },
    career: [
      { years: "2022–", team: "Atlanta Falcons", type: "NFL · on 5th-year option" },
      { years: "2019–2021", team: "USC", type: "College" },
    ],
  },
  {
    id: "dotson",
    name: "Jahan Dotson",
    number: 4,
    position: "WR",
    posSlot: "Z",
    positionGroup: "offense",
    depthRank: 2,
    height: 71, weight: 178, age: 26, experience: 5,
    college: "Penn State",
    acquired: "fa-2026-2yr",
    stats: { receptions: 31, recYds: 366, recTDs: 2, targets: 54 },
    form: 6.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4361409.png",
    contract: { years: 2, total: 17000000, guaranteed: 8500000, apy: 8500000, throughYear: 2027, cap2026: 7500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2024–2025", team: "Philadelphia Eagles", type: "NFL · Super Bowl LIX champ" },
      { years: "2022–2023", team: "Washington Commanders", type: "NFL" },
    ],
  },
  {
    id: "zaccheaus",
    name: "Olamide Zaccheaus",
    number: 14,
    position: "WR",
    posSlot: "SLOT",
        stRoles: ["PR"],
    stRank: {"PR":2},
    positionGroup: "offense",
    depthRank: 2,
    height: 70, weight: 193, age: 28, experience: 8,
    college: "Virginia",
    acquired: "fa-2026",
    stats: { receptions: 39, recYds: 313, recTDs: 2 },
    form: 6.6,
    status: "active",
    injuryNote: "Slot return · drafted by ATL 2019, back from CHI",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3917914.png",
    contract: { years: 1, total: 2400000, guaranteed: 1000000, apy: 2400000, throughYear: 2026, cap2026: 2400000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL · 2nd stint" },
      { years: "2025", team: "Chicago Bears", type: "NFL" },
      { years: "2024", team: "Washington Commanders", type: "NFL" },
      { years: "2023", team: "Philadelphia Eagles", type: "NFL" },
      { years: "2019–2022", team: "Atlanta Falcons", type: "NFL" },
    ],
  },
  {
    id: "casey-washington",
    name: "Casey Washington",
    number: 82,
    position: "WR",
    posSlot: "X",
    positionGroup: "offense",
    depthRank: 3,
    height: 75, weight: 200, age: 23, experience: 3,
    college: "Illinois",
    acquired: "draft-2024-R6",
    stats: { receptions: 12, recYds: 142, recTDs: 1 },
    form: 6.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4428796.png",
    contract: { years: 4, total: 4250000, guaranteed: 240000, apy: 1062500, throughYear: 2027, cap2026: 950000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "drummond",
    name: "Dylan Drummond",
    number: 80,
    position: "WR",
    posSlot: "SLOT",
        stRoles: ["KR","GUNNER"],
    stRank: {"KR":2,"GUNNER":3},
    positionGroup: "offense",
    depthRank: 4,
    height: 71, weight: 188, age: 25, experience: 2,
    college: "Eastern Michigan",
    acquired: "fa-2025-UDFA",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4363551.png",
    contract: { years: 1, total: 960000, guaranteed: 0, apy: 960000, throughYear: 2026, cap2026: 960000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "blair-wr",
    name: "Chris Blair",
    number: 19,
    position: "WR",
    posSlot: "X",
    positionGroup: "offense",
    depthRank: 4,
    height: 75, weight: 205, age: 25, experience: 2,
    college: "LSU",
    acquired: "fa-2024-UDFA",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Camp / PS · sized X",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4369886.png",
    contract: { years: 1, total: 1010000, guaranteed: 0, apy: 1010000, throughYear: 2026, cap2026: 1010000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // TIGHT ENDS
  // =========================================
  {
    id: "pitts",
    name: "Kyle Pitts",
    number: 8,
    position: "TE",
    positionGroup: "offense",
    depthRank: 1,
    height: 78, weight: 245, age: 25, experience: 6,
    college: "Florida",
    acquired: "draft-2021-R1-P4",
    stats: { receptions: 58, recYds: 694, recTDs: 4, targets: 92 },
    form: 7.3,
    status: "active",
    injuryNote: "Franchise tagged for 2026 · $14.1M",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4360248.png",
    contract: { years: 1, total: 14124000, guaranteed: 14124000, apy: 14124000, throughYear: 2026, cap2026: 14124000 },
    career: [
      { years: "2021–", team: "Atlanta Falcons", type: "NFL · franchise-tagged" },
      { years: "2018–2020", team: "Florida", type: "College · John Mackey Award" },
    ],
  },
  {
    id: "hooper",
    name: "Austin Hooper",
    number: 81,
    position: "TE",
    positionGroup: "offense",
    depthRank: 2,
    height: 76, weight: 254, age: 31, experience: 10,
    college: "Stanford",
    acquired: "fa-2026",
    stats: { receptions: 26, recYds: 259, recTDs: 3 },
    form: 6.5,
    status: "active",
    injuryNote: "Reunion · Falcons 2016–19, Super Bowl LI roster",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3043275.png",
    contract: { years: 1, total: 3000000, guaranteed: 1500000, apy: 3000000, throughYear: 2026, cap2026: 3000000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2023–2025", team: "New England Patriots", type: "NFL" },
      { years: "2016–2019", team: "Atlanta Falcons", type: "NFL · 2x Pro Bowl" },
    ],
  },
  {
    id: "woerner",
    name: "Charlie Woerner",
    number: 89,
    position: "TE",
    positionGroup: "offense",
    depthRank: 3,
    height: 77, weight: 243, age: 28, experience: 6,
    college: "Georgia",
    acquired: "fa-2024",
    stats: { receptions: 14, recYds: 111, recTDs: 1 },
    form: 6.4,
    status: "active",
    injuryNote: "Potential cut candidate · $4.75M 2026",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4035020.png",
    contract: { years: 3, total: 12000000, guaranteed: 6000000, apy: 4000000, throughYear: 2026, cap2026: 4750000 },
    career: [
      { years: "2024–", team: "Atlanta Falcons", type: "NFL" },
    ],
  },
  {
    id: "joshua-simon",
    name: "Joshua Simon",
    number: 47,
    position: "TE",
    positionGroup: "offense",
    depthRank: 4,
    height: 76, weight: 240, age: 24, experience: 2,
    college: "South Carolina",
    acquired: "fa-2025-UDFA",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Camp / 4th TE · move-piece",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4430482.png",
    contract: { years: 1, total: 960000, guaranteed: 0, apy: 960000, throughYear: 2026, cap2026: 960000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // OFFENSIVE LINE
  // =========================================
  {
    id: "matthews",
    name: "Jake Matthews",
    number: 70,
    position: "OT",
    posSlot: "LT",
    positionGroup: "offense",
    depthRank: 1,
    height: 77, weight: 309, age: 33, experience: 12,
    college: "Texas A&M",
    acquired: "draft-2014-R1-P6",
    stats: {},
    form: 8.5,
    status: "active",
    injuryNote: "LT · restructured March 2026 (cleared $10.5M)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/16713.png",
    contract: { years: 3, total: 55500000, guaranteed: 0, apy: 18500000, throughYear: 2027, cap2026: 15500000 },
    career: [
      { years: "2014–", team: "Atlanta Falcons", type: "NFL · Pro Bowl 2022" },
    ],
  },
  {
    id: "bergeron",
    name: "Matthew Bergeron",
    number: 65,
    position: "OG",
    posSlot: "LG",
    positionGroup: "offense",
    depthRank: 1,
    height: 77, weight: 322, age: 25, experience: 3,
    college: "Syracuse",
    acquired: "draft-2023-R2",
    stats: {},
    form: 7.8,
    status: "active",
    injuryNote: "LG · extension candidate",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4568510.png",
    contract: { years: 4, total: 9800000, guaranteed: 5200000, apy: 2450000, throughYear: 2026, cap2026: 2630000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "neuzil",
    name: "Ryan Neuzil",
    number: 66,
    position: "C",
    posSlot: "LG",
    positionGroup: "offense",
    depthRank: 1,
    height: 75, weight: 297, age: 27, experience: 5,
    college: "Appalachian State",
    acquired: "draft-2021-UDFA",
    stats: {},
    form: 7.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4036444.png",
    contract: { years: 2, total: 7500000, guaranteed: 3750000, apy: 3750000, throughYear: 2026, cap2026: 3750000 },
    career: [{ years: "2021–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "lindstrom",
    name: "Chris Lindstrom",
    number: 63,
    position: "OG",
    posSlot: "RG",
    positionGroup: "offense",
    depthRank: 1,
    height: 76, weight: 310, age: 29, experience: 7,
    college: "Boston College",
    acquired: "draft-2019-R1-P14",
    stats: {},
    form: 9.3,
    status: "active",
    injuryNote: "RG · 2x All-Pro · restructure candidate",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3672833.png",
    contract: { years: 5, total: 102500000, guaranteed: 55000000, apy: 20500000, throughYear: 2028, cap2026: 19500000 },
    career: [
      { years: "2019–", team: "Atlanta Falcons", type: "NFL · 3x Pro Bowl, 2x All-Pro" },
    ],
  },
  {
    id: "taylor",
    name: "Jawaan Taylor",
    number: 74,
    position: "OT",
    posSlot: "RT",
    positionGroup: "offense",
    depthRank: 1,
    height: 77, weight: 325, age: 28, experience: 7,
    college: "Florida",
    acquired: "fa-2026",
    stats: {},
    form: 7.5,
    status: "active",
    injuryNote: "RT · ex-Chiefs · signed 4/9 after McGary retirement",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4034961.png",
    contract: { years: 1, total: 5000000, guaranteed: 3000000, apy: 5000000, throughYear: 2026, cap2026: 5000000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL · 1yr/$5M + $1M incentives" },
      { years: "2023–2025", team: "Kansas City Chiefs", type: "NFL · Super Bowl LVIII" },
    ],
  },
  {
    id: "nelson",
    name: "Jack Nelson",
    number: 73,
    position: "OT",
    posSlot: "LT",
    positionGroup: "offense",
    depthRank: 2,
    height: 79, weight: 315, age: 24, experience: 2,
    college: "Wisconsin",
    acquired: "draft-2025-R7",
    stats: {},
    form: 6.5,
    status: "active",
    injuryNote: "Backup LT",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4693369.png",
    contract: { years: 4, total: 4200000, guaranteed: 100000, apy: 1050000, throughYear: 2028, cap2026: 920000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "hinton",
    name: "Kyle Hinton",
    number: 68,
    position: "OG",
    posSlot: "LG",
    positionGroup: "offense",
    depthRank: 2,
    height: 74, weight: 302, age: 27, experience: 5,
    college: "Washburn",
    acquired: "fa-2023",
    stats: {},
    form: 6.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4682831.png",
    contract: { years: 2, total: 3500000, guaranteed: 750000, apy: 1750000, throughYear: 2026, cap2026: 1750000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "levin",
    name: "Corey Levin",
    number: 67,
    position: "C",
    positionGroup: "offense",
    depthRank: 2,
    height: 75, weight: 300, age: 30, experience: 7,
    college: "Chattanooga",
    acquired: "fa-2023",
    stats: {},
    form: 6.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/2973637.png",
    contract: { years: 2, total: 3100000, guaranteed: 500000, apy: 1550000, throughYear: 2026, cap2026: 1550000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "stueber",
    name: "Andrew Stueber",
    number: 78,
    position: "OG",
    posSlot: "RG",
    positionGroup: "offense",
    depthRank: 2,
    height: 79, weight: 325, age: 25, experience: 3,
    college: "Michigan",
    acquired: "fa-2024",
    stats: {},
    form: 6.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4258207.png",
    contract: { years: 1, total: 1200000, guaranteed: 50000, apy: 1200000, throughYear: 2026, cap2026: 1200000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "norton",
    name: "Storm Norton",
    number: 72,
    position: "OT",
    posSlot: "RT",
    positionGroup: "offense",
    depthRank: 3,
    height: 80, weight: 325, age: 31, experience: 8,
    college: "Toledo",
    acquired: "fa-2024",
    stats: {},
    form: 6.1,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/2973014.png",
    contract: { years: 1, total: 1500000, guaranteed: 200000, apy: 1500000, throughYear: 2026, cap2026: 1500000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "jerrell",
    name: "Michael Jerrell",
    number: 72,
    position: "OT",
    posSlot: "LT",
    positionGroup: "offense",
    depthRank: 4,
    height: 78, weight: 313, age: 25, experience: 2,
    college: "Findlay",
    acquired: "draft-2024-R7",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Swing tackle · D-II development project",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/5209093.png",
    contract: { years: 4, total: 4150000, guaranteed: 100000, apy: 1037500, throughYear: 2027, cap2026: 920000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // DEFENSIVE LINE
  // =========================================
  {
    id: "dorlus",
    name: "Brandon Dorlus",
    number: 54,
    position: "DT",
    posSlot: "3T",
    positionGroup: "defense",
    depthRank: 1,
    height: 75, weight: 285, age: 24, experience: 3,
    college: "Oregon",
    acquired: "draft-2024-R4",
    stats: { tackles: 52, solo: 28, tfl: 9, sacks: 8.5, qb_hits: 14 },
    form: 8.4,
    status: "active",
    injuryNote: "Breakout 2025 · 8.5 sacks",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4427090.png",
    contract: { years: 4, total: 4800000, guaranteed: 1900000, apy: 1200000, throughYear: 2027, cap2026: 1100000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "harrison",
    name: "Zach Harrison",
    number: 96,
    position: "DE",
    posSlot: "LDE",
    positionGroup: "defense",
    depthRank: 1,
    height: 78, weight: 272, age: 24, experience: 4,
    college: "Ohio State",
    acquired: "draft-2023-R3",
    stats: { tackles: 41, tfl: 5, sacks: 3.5 },
    form: 7.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4426412.png",
    contract: { years: 4, total: 5400000, guaranteed: 2100000, apy: 1350000, throughYear: 2026, cap2026: 1440000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "maason-smith",
    name: "Maason Smith",
    number: 92,
    position: "DT",
    posSlot: "1T",
    positionGroup: "defense",
    depthRank: 1,
    height: 77, weight: 306, age: 23, experience: 3,
    college: "LSU",
    acquired: "trade-2026-JAX",
    stats: { tackles: 32, tfl: 3, sacks: 3 },
    form: 6.8,
    status: "active",
    injuryNote: "Acquired 4/17 in DT swap for Ruke Orhorhoro",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4431567.png",
    contract: { years: 4, total: 5900000, guaranteed: 2900000, apy: 1475000, throughYear: 2027, cap2026: 1420000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2024–2025", team: "Jacksonville Jaguars", type: "NFL · 2024 R2 #48" },
    ],
  },
  {
    id: "chris-williams-dl",
    name: "Chris Williams",
    number: 98,
    position: "DT",
    posSlot: "3T",
    positionGroup: "defense",
    depthRank: 2,
    height: 76, weight: 295, age: 26, experience: 4,
    college: "Wagner",
    acquired: "fa-2026",
    stats: { tackles: 29, sacks: 3.5 },
    form: 6.8,
    status: "active",
    injuryNote: "Ex-Bears · 1-yr deal",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4034530.png",
    contract: { years: 1, total: 2800000, guaranteed: 1500000, apy: 2800000, throughYear: 2026, cap2026: 2800000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Chicago Bears", type: "NFL" },
    ],
  },
  {
    id: "cam-thomas",
    name: "Cameron Thomas",
    number: 99,
    position: "DE",
    posSlot: "RDE",
    positionGroup: "defense",
    depthRank: 2,
    height: 76, weight: 267, age: 26, experience: 5,
    college: "San Diego State",
    acquired: "fa-2026",
    stats: { tackles: 24, sacks: 2 },
    form: 6.4,
    status: "active",
    injuryNote: "Ex-Browns · 1-yr deal",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4361510.png",
    contract: { years: 1, total: 2500000, guaranteed: 1200000, apy: 2500000, throughYear: 2026, cap2026: 2500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Arizona / Cleveland", type: "NFL" },
    ],
  },
  {
    id: "hand",
    name: "Da'Shawn Hand",
    number: 93,
    position: "DT",
    posSlot: "3T",
    positionGroup: "defense",
    depthRank: 3,
    height: 75, weight: 297, age: 30, experience: 8,
    college: "Alabama",
    acquired: "fa-2026",
    stats: { tackles: 22, tfl: 5 },
    form: 6.5,
    status: "active",
    injuryNote: "Partial replacement for Onyemata · 1-yr / $3M",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3126352.png",
    contract: { years: 1, total: 3000000, guaranteed: 1500000, apy: 3000000, throughYear: 2026, cap2026: 3000000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2024–2025", team: "Los Angeles Chargers", type: "NFL" },
      { years: "2018–2023", team: "Detroit / Tennessee", type: "NFL" },
    ],
  },
  {
    id: "lacale-london",
    name: "LaCale London",
    number: 94,
    position: "DT",
    posSlot: "1T",
    positionGroup: "defense",
    depthRank: 3,
    height: 77, weight: 290, age: 25, experience: 3,
    college: "Western Illinois",
    acquired: "fa-2025",
    stats: { tackles: 14, sacks: 1 },
    form: 6.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4376288.png",
    contract: { years: 1, total: 1100000, guaranteed: 100000, apy: 1100000, throughYear: 2026, cap2026: 1100000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "garcia-de",
    name: "Elijah Garcia",
    number: 91,
    position: "DE",
    posSlot: "RDE",
    positionGroup: "defense",
    depthRank: 3,
    height: 75, weight: 296, age: 26, experience: 4,
    college: "Rice",
    acquired: "fa-2026",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Rotational base end · ex-Broncos",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4039170.png",
    contract: { years: 1, total: 1300000, guaranteed: 200000, apy: 1300000, throughYear: 2026, cap2026: 1300000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2023–2025", team: "Denver Broncos", type: "NFL" },
    ],
  },

  // =========================================
  // EDGE / OLB
  // =========================================
  {
    id: "jalon-walker",
    name: "Jalon Walker",
    number: 11,
    position: "EDGE",
    posSlot: "REDGE",
    positionGroup: "defense",
    depthRank: 1,
    height: 74, weight: 245, age: 22, experience: 2,
    college: "Georgia",
    acquired: "draft-2025-R1-P15",
    stats: { tackles: 62, tfl: 10, sacks: 5.5, ff: 1 },
    form: 8.5,
    status: "active",
    injuryNote: "Rookie-year starter · 2024 Butkus Award",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4685597.png",
    contract: { years: 4, total: 19200000, guaranteed: 19200000, apy: 4800000, throughYear: 2028, cap2026: 4400000 },
    career: [
      { years: "2025–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2024", team: "Georgia", type: "College · 2x CFP champ" },
    ],
  },
  {
    id: "pearce-jr",
    name: "James Pearce Jr.",
    number: 27,
    position: "EDGE",
    posSlot: "LEDGE",
    positionGroup: "defense",
    depthRank: 2,
    height: 77, weight: 245, age: 22, experience: 2,
    college: "Tennessee",
    acquired: "draft-2025-R1-P26",
    stats: { tackles: 31, sacks: 4.5 },
    form: 7.6,
    status: "active",
    injuryNote: "Rookie contributor · high-upside",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/5081394.png",
    contract: { years: 4, total: 14500000, guaranteed: 14500000, apy: 3625000, throughYear: 2028, cap2026: 3350000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "ojulari",
    name: "Azeez Ojulari",
    number: 51,
    position: "EDGE",
    posSlot: "LEDGE",
    positionGroup: "defense",
    depthRank: 2,
    height: 74, weight: 240, age: 26, experience: 6,
    college: "Georgia",
    acquired: "fa-2026-1yr",
    stats: { tackles: 28, sacks: 6, ff: 1 },
    form: 7.3,
    status: "active",
    injuryNote: "Ex-Giants · homecoming (UGA)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4379409.png",
    contract: { years: 1, total: 4000000, guaranteed: 2500000, apy: 4000000, throughYear: 2026, cap2026: 4000000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2021–2025", team: "New York Giants", type: "NFL" },
    ],
  },
  {
    id: "trice",
    name: "Bralen Trice",
    number: 48,
    position: "EDGE",
    posSlot: "REDGE",
    positionGroup: "defense",
    depthRank: 3,
    height: 76, weight: 245, age: 24, experience: 2,
    college: "Washington",
    acquired: "draft-2024-R3",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Returning from 2024 ACL · clean rookie tape pending",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4428713.png",
    contract: { years: 4, total: 5800000, guaranteed: 1300000, apy: 1450000, throughYear: 2027, cap2026: 1180000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "deangelo-malone",
    name: "DeAngelo Malone",
    number: 50,
    position: "EDGE",
    posSlot: "LEDGE",
    positionGroup: "defense",
    depthRank: 4,
    height: 75, weight: 240, age: 27, experience: 5,
    college: "Western Kentucky",
    acquired: "fa-2025",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Rotational rusher · ex-Titans",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4243457.png",
    contract: { years: 1, total: 1300000, guaranteed: 100000, apy: 1300000, throughYear: 2026, cap2026: 1300000 },
    career: [
      { years: "2025–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2024", team: "Tennessee Titans", type: "NFL" },
    ],
  },

  // =========================================
  // LINEBACKERS
  // =========================================
  {
    id: "deablo",
    name: "Divine Deablo",
    number: 0,
    position: "LB",
    posSlot: "MIKE",
    positionGroup: "defense",
    depthRank: 1,
    height: 75, weight: 226, age: 27, experience: 5,
    college: "Virginia Tech",
    acquired: "fa-2026",
    stats: { tackles: 92, tfl: 7, sacks: 2, int_def: 1 },
    form: 8.0,
    status: "active",
    injuryNote: "MIKE · 3yr/$30M FA splash from LV",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4037626.png",
    contract: { years: 3, total: 30000000, guaranteed: 18000000, apy: 10000000, throughYear: 2028, cap2026: 8500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2021–2025", team: "Las Vegas Raiders", type: "NFL" },
    ],
  },
  {
    id: "christian-harris",
    name: "Christian Harris",
    number: 45,
    position: "LB",
    posSlot: "WILL",
    positionGroup: "defense",
    depthRank: 1,
    height: 73, weight: 230, age: 25, experience: 5,
    college: "Alabama",
    acquired: "trade-2025",
    stats: { tackles: 74, tfl: 6, sacks: 1.5 },
    form: 7.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4567099.png",
    contract: { years: 1, total: 3300000, guaranteed: 3300000, apy: 3300000, throughYear: 2026, cap2026: 3300000 },
    career: [
      { years: "2025–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2024", team: "Houston Texans", type: "NFL" },
    ],
  },
  {
    id: "andersen",
    name: "Troy Andersen",
    number: 44,
    position: "LB",
    posSlot: "MIKE",
        stRoles: ["PP"],
    stRank: {"PP":3},
    positionGroup: "defense",
    depthRank: 2,
    height: 75, weight: 243, age: 26, experience: 5,
    college: "Montana State",
    acquired: "draft-2022-R2",
    stats: { tackles: 31 },
    form: 6.6,
    status: "questionable",
    injuryNote: "Shoulder recovery from 2025 IR stint",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4247807.png",
    contract: { years: 1, total: 3420000, guaranteed: 3420000, apy: 3420000, throughYear: 2026, cap2026: 3420000 },
    career: [{ years: "2022–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "tindall",
    name: "Channing Tindall",
    number: 55,
    position: "LB",
    posSlot: "WILL",
    positionGroup: "defense",
    depthRank: 2,
    height: 74, weight: 230, age: 26, experience: 5,
    college: "Georgia",
    acquired: "fa-2026",
    stats: { tackles: 42 },
    form: 6.6,
    status: "active",
    injuryNote: "Ex-Cardinals · another UGA addition",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4379414.png",
    contract: { years: 1, total: 1800000, guaranteed: 500000, apy: 1800000, throughYear: 2026, cap2026: 1800000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "Miami / Arizona", type: "NFL" },
    ],
  },
  {
    id: "bertrand",
    name: "JD Bertrand",
    number: 40,
    position: "LB",
    posSlot: "MIKE",
        stRoles: ["PP"],
    stRank: {"PP":1},
    positionGroup: "defense",
    depthRank: 3,
    height: 73, weight: 235, age: 24, experience: 3,
    college: "Notre Dame",
    acquired: "draft-2024-R5",
    stats: { tackles: 18 },
    form: 6.2,
    status: "active",
    injuryNote: "Special teams ace",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4428872.png",
    contract: { years: 4, total: 4400000, guaranteed: 200000, apy: 1100000, throughYear: 2027, cap2026: 970000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "verdon",
    name: "Malik Verdon",
    number: 43,
    position: "LB",
    posSlot: "WILL",
    positionGroup: "defense",
    depthRank: 4,
    height: 76, weight: 230, age: 23, experience: 1,
    college: "Iowa State",
    acquired: "fa-2025-UDFA",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Hybrid LB/S · sub-package",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4684636.png",
    contract: { years: 1, total: 960000, guaranteed: 0, apy: 960000, throughYear: 2026, cap2026: 960000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // CORNERBACKS
  // =========================================
  {
    id: "terrell",
    name: "A.J. Terrell",
    number: 24,
    position: "CB",
    posSlot: "LCB",
    positionGroup: "defense",
    depthRank: 1,
    height: 73, weight: 195, age: 27, experience: 7,
    college: "Clemson",
    acquired: "draft-2020-R1-P16",
    stats: { tackles: 68, int_def: 2, pass_def: 13 },
    form: 8.2,
    status: "active",
    injuryNote: "CB1 · paid like one (4yr/$81M extension in 2024)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4239995.png",
    contract: { years: 4, total: 81000000, guaranteed: 43500000, apy: 20250000, throughYear: 2028, cap2026: 19200000 },
    career: [{ years: "2020–", team: "Atlanta Falcons", type: "NFL · Pro Bowl 2021" }],
  },
  {
    id: "hughes",
    name: "Mike Hughes",
    number: 21,
    position: "CB",
    posSlot: "RCB",
    positionGroup: "defense",
    depthRank: 1,
    height: 70, weight: 190, age: 29, experience: 8,
    college: "UCF",
    acquired: "fa-2023",
    stats: { tackles: 57, int_def: 1, pass_def: 8 },
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3895841.png",
    contract: { years: 2, total: 9000000, guaranteed: 3000000, apy: 4500000, throughYear: 2026, cap2026: 4200000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "brooks-cb",
    name: "Natrone Brooks",
    number: 35,
    position: "CB",
    posSlot: "NICKEL",
        stRoles: ["GUNNER"],
    stRank: {"GUNNER":2},
    positionGroup: "defense",
    depthRank: 2,
    height: 71, weight: 190, age: 27, experience: 4,
    college: "Mississippi Valley State",
    acquired: "extension-2026",
    stats: { tackles: 32, pass_def: 4 },
    form: 6.8,
    status: "active",
    injuryNote: "Extended March 2026",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4689989.png",
    contract: { years: 2, total: 4500000, guaranteed: 2000000, apy: 2250000, throughYear: 2027, cap2026: 2250000 },
    career: [{ years: "2024–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "phillips-cb",
    name: "Clark Phillips III",
    number: 22,
    position: "CB",
    posSlot: "NICKEL",
    positionGroup: "defense",
    depthRank: 3,
    height: 70, weight: 184, age: 24, experience: 4,
    college: "Utah",
    acquired: "draft-2023-R4",
    stats: { tackles: 28, int_def: 2, pass_def: 4 },
    form: 6.7,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4429067.png",
    contract: { years: 4, total: 4800000, guaranteed: 1600000, apy: 1200000, throughYear: 2026, cap2026: 1250000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "henderson-cb",
    name: "C.J. Henderson",
    number: 39,
    position: "CB",
    posSlot: "RCB",
    positionGroup: "defense",
    depthRank: 2,
    height: 73, weight: 200, age: 27, experience: 6,
    college: "Florida",
    acquired: "fa-2026",
    stats: { tackles: 28, pass_def: 5 },
    form: 6.6,
    status: "active",
    injuryNote: "Reclamation · ex-#9 overall (2020 JAX)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4240596.png",
    contract: { years: 1, total: 2200000, guaranteed: 750000, apy: 2200000, throughYear: 2026, cap2026: 2200000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2021–2025", team: "Carolina Panthers", type: "NFL" },
      { years: "2020", team: "Jacksonville Jaguars", type: "NFL · 1st-round pick" },
    ],
  },
  {
    id: "holmes-cb",
    name: "Darnay Holmes",
    number: 30,
    position: "CB",
    posSlot: "NICKEL",
    positionGroup: "defense",
    depthRank: 3,
    height: 70, weight: 195, age: 28, experience: 7,
    college: "UCLA",
    acquired: "fa-2026",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Slot specialist · ex-Giants",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4242973.png",
    contract: { years: 1, total: 1300000, guaranteed: 100000, apy: 1300000, throughYear: 2026, cap2026: 1300000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2020–2025", team: "New York Giants", type: "NFL" },
    ],
  },
  {
    id: "ford-cb",
    name: "Mike Ford Jr.",
    number: 28,
    position: "CB",
    posSlot: "LCB",
        stRoles: ["GUNNER"],
    stRank: {"GUNNER":1},
    positionGroup: "defense",
    depthRank: 4,
    height: 71, weight: 195, age: 31, experience: 8,
    college: "Southeast Missouri State",
    acquired: "fa-2026",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "ST captain candidate",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3050916.png",
    contract: { years: 1, total: 1300000, guaranteed: 200000, apy: 1300000, throughYear: 2026, cap2026: 1300000 },
    career: [{ years: "2026–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "bowman",
    name: "Billy Bowman Jr.",
    number: 33,
    position: "CB",
    posSlot: "NICKEL",
    positionGroup: "defense",
    depthRank: 4,
    height: 69, weight: 192, age: 22, experience: 1,
    college: "Oklahoma",
    acquired: "draft-2025-R4",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Nickel/safety hybrid",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4431194.png",
    contract: { years: 4, total: 5200000, guaranteed: 950000, apy: 1300000, throughYear: 2028, cap2026: 1100000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "bryant-cb",
    name: "Cobee Bryant",
    number: 37,
    position: "CB",
    posSlot: "RCB",
        stRoles: ["GUNNER"],
    stRank: {"GUNNER":4},
    positionGroup: "defense",
    depthRank: 4,
    height: 72, weight: 175, age: 23, experience: 1,
    college: "Kansas",
    acquired: "fa-2025-UDFA",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4429324.png",
    contract: { years: 1, total: 960000, guaranteed: 0, apy: 960000, throughYear: 2026, cap2026: 960000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // SAFETIES
  // =========================================
  {
    id: "bates",
    name: "Jessie Bates III",
    number: 3,
    position: "S",
    posSlot: "FS",
    positionGroup: "defense",
    depthRank: 1,
    height: 74, weight: 200, age: 29, experience: 9,
    college: "Wake Forest",
    acquired: "fa-2024",
    stats: { tackles: 98, int_def: 3, pass_def: 9, ff: 1 },
    form: 9.1,
    status: "active",
    injuryNote: "All-Pro · restructure candidate",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3919512.png",
    contract: { years: 4, total: 64000000, guaranteed: 36000000, apy: 16000000, throughYear: 2027, cap2026: 16800000 },
    career: [
      { years: "2024–", team: "Atlanta Falcons", type: "NFL · All-Pro 2024" },
      { years: "2018–2023", team: "Cincinnati Bengals", type: "NFL · Super Bowl LVI" },
    ],
  },
  {
    id: "xavier-watts",
    name: "Xavier Watts",
    number: 31,
    position: "S",
    posSlot: "SS",
    positionGroup: "defense",
    depthRank: 1,
    height: 72, weight: 205, age: 23, experience: 2,
    college: "Notre Dame",
    acquired: "draft-2025-R3",
    stats: { tackles: 58, int_def: 4, pass_def: 6 },
    form: 8.2,
    status: "active",
    injuryNote: "Rookie-year impact · ballhawk",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4431005.png",
    contract: { years: 4, total: 5100000, guaranteed: 4600000, apy: 1275000, throughYear: 2028, cap2026: 1170000 },
    career: [
      { years: "2025–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2021–2024", team: "Notre Dame", type: "College · 2x Bronko Nagurski winner" },
    ],
  },
  {
    id: "sydney-brown",
    name: "Sydney Brown",
    number: 29,
    position: "S",
    posSlot: "SS",
    positionGroup: "defense",
    depthRank: 2,
    height: 70, weight: 205, age: 26, experience: 4,
    college: "Illinois",
    acquired: "trade-2026-PHI",
    stats: { tackles: 41, int_def: 1, pass_def: 3 },
    form: 7.0,
    status: "active",
    injuryNote: "Acquired Mar 20 from Philly in pick swap",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4360386.png",
    contract: { years: 1, total: 1400000, guaranteed: 200000, apy: 1400000, throughYear: 2026, cap2026: 1400000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2023–2025", team: "Philadelphia Eagles", type: "NFL · Super Bowl LIX champ" },
    ],
  },
  {
    id: "hellams",
    name: "DeMarcco Hellams",
    number: 23,
    position: "S",
    posSlot: "SS",
        stRoles: ["PP"],
    stRank: {"PP":2},
    positionGroup: "defense",
    depthRank: 3,
    height: 72, weight: 205, age: 25, experience: 4,
    college: "Alabama",
    acquired: "draft-2023-R7",
    stats: { tackles: 36 },
    form: 6.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4567111.png",
    contract: { years: 4, total: 3800000, guaranteed: 200000, apy: 950000, throughYear: 2026, cap2026: 1100000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "jammie-robinson",
    name: "Jammie Robinson",
    number: 34,
    position: "S",
    posSlot: "FS",
        stRoles: ["PP","GUNNER"],
    stRank: {"PP":4,"GUNNER":5},
    positionGroup: "defense",
    depthRank: 3,
    height: 71, weight: 207, age: 25, experience: 3,
    college: "Florida State",
    acquired: "draft-2023-R5",
    stats: {},
    form: 6.4,
    status: "active",
    injuryNote: "Box safety / sub-package",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4430411.png",
    contract: { years: 4, total: 4350000, guaranteed: 220000, apy: 1087500, throughYear: 2026, cap2026: 1050000 },
    career: [{ years: "2023–", team: "Atlanta Falcons", type: "NFL" }],
  },
  {
    id: "tysheem-johnson",
    name: "Tysheem Johnson",
    number: 41,
    position: "S",
    posSlot: "FS",
    positionGroup: "defense",
    depthRank: 4,
    height: 70, weight: 198, age: 23, experience: 1,
    college: "Oregon",
    acquired: "fa-2025-UDFA",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4431405.png",
    contract: { years: 1, total: 960000, guaranteed: 0, apy: 960000, throughYear: 2026, cap2026: 960000 },
    career: [{ years: "2025–", team: "Atlanta Falcons", type: "NFL" }],
  },

  // =========================================
  // 2026 DRAFT CLASS — rookies report May 1 / 8 for minicamp
  // =========================================
  {
    id: "avieon-terrell",
    name: "Avieon Terrell",
    number: 12,
    position: "CB",
    posSlot: "RCB",
    positionGroup: "defense",
    depthRank: 2,
    height: 71, weight: 184, age: 21, experience: 0,
    college: "Clemson",
    acquired: "draft-2026-R2-P48",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Hamstring re-aggravation at private pro day; expected fully cleared by minicamp",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4870988.png",
    contract: { years: 4, total: 8500000, guaranteed: 4200000, apy: 2125000, throughYear: 2029, cap2026: 1400000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL · 1st known starting-CB sibling tandem" },
      { years: "2022–2025", team: "Clemson", type: "College · A.J. Terrell's brother" },
    ],
  },
  {
    id: "zachariah-branch",
    name: "Zachariah Branch",
    number: 17,
    position: "WR",
    posSlot: "SLOT",
        stRoles: ["KR","PR"],
    stRank: {"KR":1,"PR":1},
    positionGroup: "offense",
    depthRank: 3,
    height: 69, weight: 178, age: 21, experience: 0,
    college: "Georgia",
    acquired: "draft-2026-R3-P79",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4870612.png",
    contract: { years: 4, total: 5800000, guaranteed: 1850000, apy: 1450000, throughYear: 2029, cap2026: 1100000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2025", team: "Georgia", type: "College · transfer from USC" },
      { years: "2023–2024", team: "USC", type: "College · 2023 Jet Award winner" },
    ],
  },
  {
    id: "kendal-daniels",
    name: "Kendal Daniels",
    number: 53,
    position: "LB",
    posSlot: "WILL",
    positionGroup: "defense",
    depthRank: 3,
    height: 76, weight: 222, age: 23, experience: 0,
    college: "Oklahoma",
    acquired: "draft-2026-R4-P134",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4595343.png",
    contract: { years: 4, total: 4750000, guaranteed: 700000, apy: 1187500, throughYear: 2029, cap2026: 900000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2025", team: "Oklahoma", type: "College · 'Cheetah' hybrid LB · 13 GS, 9 TFL" },
      { years: "2022–2024", team: "Oklahoma State", type: "College · safety" },
    ],
  },
  {
    id: "anterio-thompson",
    name: "Anterio Thompson",
    number: 98,
    position: "DT",
    posSlot: "1T",
    positionGroup: "defense",
    depthRank: 4,
    height: 74, weight: 306, age: 23, experience: 0,
    college: "Washington",
    acquired: "draft-2026-R6-P208",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/5150660.png",
    contract: { years: 4, total: 4250000, guaranteed: 130000, apy: 1062500, throughYear: 2029, cap2026: 850000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2021–2025", team: "Washington", type: "College · 4.73 forty / 3 blocked punts in 2025" },
    ],
  },
  {
    id: "harold-perkins",
    name: "Harold Perkins Jr.",
    number: 56,
    position: "LB",
    posSlot: "WILL",
    positionGroup: "defense",
    depthRank: 4,
    height: 73, weight: 220, age: 22, experience: 0,
    college: "LSU",
    acquired: "draft-2026-R6-P215",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: "Returning from torn right ACL (2024); ran 4.45 at pro day",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4685502.png",
    contract: { years: 4, total: 4450000, guaranteed: 100000, apy: 1112500, throughYear: 2029, cap2026: 850000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2022–2025", team: "LSU", type: "College · 2022 Freshman All-American" },
    ],
  },
  {
    id: "ethan-onianwa",
    name: "Ethan Onianwa",
    number: 75,
    position: "OT",
    posSlot: "RT",
    positionGroup: "offense",
    depthRank: 4,
    height: 78, weight: 333, age: 23, experience: 0,
    college: "Ohio State",
    acquired: "draft-2026-R7-P231",
    stats: {},
    form: 0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/4683194.png",
    contract: { years: 4, total: 4150000, guaranteed: 80000, apy: 1037500, throughYear: 2029, cap2026: 800000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2025", team: "Ohio State", type: "College · transfer · did not start" },
      { years: "2021–2024", team: "Rice", type: "College · 34 starts at OT" },
    ],
  },

  // =========================================
  // SPECIAL TEAMS
  // =========================================
  {
    id: "folk",
    name: "Nick Folk",
    number: 6,
    position: "K",
    positionGroup: "special",
    depthRank: 1,
    height: 73, weight: 222, age: 41, experience: 19,
    college: "Arizona",
    acquired: "fa-2026",
    stats: { fgMade: 31, fgAttempted: 35, longFG: 55, xpMade: 28, xpAttempted: 29 },
    form: 8.8,
    status: "active",
    injuryNote: "Ageless · 88.6% career FG",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/10621.png",
    contract: { years: 2, total: 5000000, guaranteed: 2000000, apy: 2500000, throughYear: 2027, cap2026: 2500000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2007–2025", team: "Dallas / Tampa / NY Jets / New England / Tennessee", type: "NFL · Pro Bowl 2023" },
    ],
  },
  {
    id: "bailey",
    name: "Jake Bailey",
    number: 16,
    position: "P",
        stRoles: ["H"],
    stRank: {"H":1},
    positionGroup: "special",
    depthRank: 1,
    height: 74, weight: 208, age: 28, experience: 7,
    college: "Stanford",
    acquired: "fa-2026-3yr",
    stats: { puntAvg: 48.2, netPuntAvg: 42.8, punts_i20: 25 },
    form: 8.4,
    status: "active",
    injuryNote: "1x All-Pro (2020)",
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3931395.png",
    contract: { years: 3, total: 9000000, guaranteed: 4000000, apy: 3000000, throughYear: 2028, cap2026: 2800000 },
    career: [
      { years: "2026–", team: "Atlanta Falcons", type: "NFL" },
      { years: "2019–2025", team: "New England / Miami", type: "NFL · 2020 All-Pro" },
    ],
  },
  {
    id: "mccullough-ls",
    name: "Liam McCullough",
    number: 49,
    position: "LS",
    positionGroup: "special",
    depthRank: 1,
    height: 74, weight: 230, age: 28, experience: 5,
    college: "Ohio State",
    acquired: "fa-2022",
    stats: {},
    form: 7.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/nfl/players/full/3915528.png",
    contract: { years: 2, total: 2700000, guaranteed: 500000, apy: 1350000, throughYear: 2026, cap2026: 1400000 },
    career: [{ years: "2022–", team: "Atlanta Falcons", type: "NFL" }],
  },
];

// =========================================
// FRONT OFFICE + COACHING STAFF
// =========================================
// Tiered roster of decision-makers. Photos sourced from atlantafalcons.com's
// Cloudinary CDN (HEAD-verified 200 OK). If a photo URL ever 404s, leave the
// image field null — the view falls back to initials.
//
// 2026 org structure (per Blank's Jan 2026 letter to fans):
//   • OWNERSHIP — Arthur Blank
//   • FOOTBALL OPS — Matt Ryan (President), Ian Cunningham (GM)
//   • BUSINESS — Greg Beadles (President & CEO)
//   • COACHING — Stefanski + coordinators

export const FRONT_OFFICE = [
  // ─── OWNERSHIP ────────────────────────────────────────────────────────────
  {
    id: "arthur-blank",
    name: "Arthur M. Blank",
    title: "Owner & Chairman",
    tier: "OWNERSHIP",
    since: 2002,
    bio: "Home Depot co-founder. Bought the Falcons in 2002 for $545M. Built Mercedes-Benz Stadium; owns Atlanta United FC and AMBSE.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/lijqsh3vasfinxnmhhxe.jpg",
  },

  // ─── FOOTBALL OPERATIONS ──────────────────────────────────────────────────
  {
    id: "matt-ryan-fo",
    name: "Matt Ryan",
    title: "President of Football Operations",
    tier: "FOOTBALL OPS",
    since: 2026,
    bio: "Falcons' all-time franchise QB (2008–2021, '16 MVP). Holds final football authority — HC and GM report to him.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/qzp3if8letihdg2hol1f.jpg",
  },
  {
    id: "ian-cunningham",
    name: "Ian Cunningham",
    title: "General Manager",
    tier: "FOOTBALL OPS",
    since: 2026,
    bio: "Hired from Chicago (Assistant GM, 2022–25). 'Build through the trenches' mandate. First draft: Branch, A. Terrell, Onianwa.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/epnbjquga4z6wlfi7gro.png",
  },

  // ─── BUSINESS / CLUB ──────────────────────────────────────────────────────
  {
    id: "greg-beadles",
    name: "Greg Beadles",
    title: "President & CEO",
    tier: "BUSINESS",
    since: 2026,
    bio: "Promoted Jan 2026, replacing Rich McKay. 23-year Falcons veteran on the business side. Hosts the Madrid game at Bernabéu Nov 8.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/ced4kse7xkadcrkamylm.jpg",
  },

  // ─── HEAD COACH ───────────────────────────────────────────────────────────
  {
    id: "kevin-stefanski",
    name: "Kevin Stefanski",
    title: "Head Coach",
    tier: "COACHING",
    since: 2026,
    bio: "Hired Jan 2026 after 6 seasons in Cleveland (2x AP Coach of the Year). Installs play-action, under-center, wide-zone DNA.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/liausetnt2rma91emlfy.jpg",
  },

  // ─── COORDINATORS ─────────────────────────────────────────────────────────
  {
    id: "tommy-rees",
    name: "Tommy Rees",
    title: "Offensive Coordinator · Play Caller",
    tier: "COORDINATORS",
    since: 2026,
    bio: "33 yrs old. Was Browns TEs coach '24 → OC mid-'25. Notre Dame QB pedigree. Stefanski: 'very comfortable' with him calling plays.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/fcevqfof9amqkjeo60pz.jpg",
  },
  {
    id: "jeff-ulbrich",
    name: "Jeff Ulbrich",
    title: "Defensive Coordinator",
    tier: "COORDINATORS",
    since: 2024,
    bio: "Retained from the previous staff. 4-3 / hybrid front. Ex-NFL LB (SF '00–'09). Drives the Walker/Pearce edge package.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/lsbimbddujis4at4mzzp.jpg",
  },
  {
    id: "craig-aukerman",
    name: "Craig Aukerman",
    title: "Special Teams Coordinator",
    tier: "COORDINATORS",
    since: 2026,
    bio: "New hire alongside Stefanski. Inherits Folk/Bailey/McCullough specialist trio plus Branch return package.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/e9snvay0ojf5awficdwp.jpg",
  },

  // ─── KEY POSITION COACHES ─────────────────────────────────────────────────
  {
    id: "bill-callahan",
    name: "Bill Callahan",
    title: "Offensive Line Coach",
    tier: "POSITION COACHES",
    since: 2026,
    bio: "Long-tenured OL guru (ex-Cowboys, Browns, Raiders HC). Reunited with Stefanski. Tasked with the Matthews / Taylor tackle build.",
    image: "https://static.clubs.nfl.com/image/upload/f_auto/falcons/w8eo7bazirbaauv79qat.jpg",
  },
];

// =========================================
// TEAM LOGOS
// =========================================
export const TEAM_LOGOS = {
  ATL: "https://static.www.nfl.com/image/private/f_auto/league/d8m7hzpsbrl6pnqht8op",
  NO: "https://static.www.nfl.com/image/private/f_auto/league/grhjkahghjkk17v43hdx",
  CAR: "https://static.www.nfl.com/image/private/f_auto/league/ervfzgrqdpnc7lh5gqwq",
  TB: "https://static.www.nfl.com/image/private/f_auto/league/v8uqiualryypwqgvwcih",
  PHI: "https://static.www.nfl.com/image/private/f_auto/league/puhrqgj71gobgdkdo6uq",
  KC: "https://static.www.nfl.com/image/private/f_auto/league/ujshjqvmnxce8m4obmvs",
  SF: "https://static.www.nfl.com/image/private/f_auto/league/dxibuyxbk0b9ua5ih9hn",
  WAS: "https://static.www.nfl.com/image/private/f_auto/league/xymxwrl1zp4xzcfsbvuf",
  DET: "https://static.www.nfl.com/image/private/f_auto/league/ocvxwnapdvwevupe4tpr",
  GB: "https://static.www.nfl.com/image/private/f_auto/league/gppfvr7n8gljgjaqux2x",
  CHI: "https://static.www.nfl.com/image/private/f_auto/league/ra0poq2ivwyahbaq86d2",
  MIN: "https://static.www.nfl.com/image/private/f_auto/league/teguylrnqqmfcwxvcmmz",
  PIT: "https://static.www.nfl.com/image/private/f_auto/league/xujg9t3t4u5nmjgr54wx",
  BAL: "https://static.www.nfl.com/image/private/f_auto/league/ucsdijmddsqcj1i9tddd",
  CIN: "https://static.www.nfl.com/image/private/f_auto/league/okxpteoliyayufypqalq",
  CLE: "https://static.www.nfl.com/image/private/f_auto/league/fgbn8acp4opvyxk13dcy",
};

// =========================================
// RSS FEEDS
// =========================================
export const RSS_FEEDS = [
  {
    name: "The Falcoholic",
    url: "https://www.thefalcoholic.com/rss/index.xml",
    color: "#A71930",
  },
  {
    name: "ESPN NFL",
    url: "https://www.espn.com/espn/rss/nfl/news",
    color: "#de0613",
  },
  {
    name: "Pro Football Rumors · Falcons",
    url: "https://www.profootballrumors.com/atlanta-falcons/feed",
    color: "#F39C12",
  },
];

// =========================================
// NEXT GAME (null during offseason)
// =========================================
export const NEXT_GAME = null;

// =========================================
// 2026 SCHEDULE
// =========================================
// Status of the full schedule release. Update once tonight's reveal lands.
//   "pre-reveal"  — before 8 PM ET Thu May 14 (only locked games shown)
//   "revealed"    — full schedule public, populate week-by-week
//   "in-season"   — games being played
export const SCHEDULE_2026_STATUS = "pre-reveal";

// Reveal moment so the countdown can tick down to 0.
export const SCHEDULE_2026_REVEAL_AT = "2026-05-14T20:00:00-04:00";

// 17 opponents are locked even pre-reveal. Each entry: { code, side, repeat }
// `side` = home | away, `repeat` = the rematch's side (since divisional opponents
// hit twice — one home, one away).
export const SCHEDULE_2026_OPPONENTS = {
  // NFC South — home + away
  divisional: [
    { code: "CAR", name: "Carolina Panthers", sides: ["home", "away"] },
    { code: "NO",  name: "New Orleans Saints", sides: ["home", "away"] },
    { code: "TB",  name: "Tampa Bay Buccaneers", sides: ["home", "away"] },
  ],
  homeOnly: [
    { code: "BAL", name: "Baltimore Ravens" },
    { code: "CHI", name: "Chicago Bears" },
    { code: "CIN", name: "Cincinnati Bengals", note: "Madrid · Bernabéu" },
    { code: "DET", name: "Detroit Lions" },
    { code: "KC",  name: "Kansas City Chiefs" },
    { code: "SF",  name: "San Francisco 49ers" },
  ],
  awayOnly: [
    { code: "CLE", name: "Cleveland Browns" },
    { code: "GB",  name: "Green Bay Packers" },
    { code: "MIN", name: "Minnesota Vikings" },
    { code: "PIT", name: "Pittsburgh Steelers" },
    { code: "WAS", name: "Washington Commanders" },
  ],
};

// 18 entries (17 games + bye). status: "confirmed" | "leaked" | "tbd" | "bye"
// Pre-reveal: only the 2 locked games carry firm data; the rest are TBD slots.
// After tonight's reveal, fill in all `tbd` rows with week/opponent/date/time.
export const SCHEDULE_2026 = [
  {
    week: 1,
    status: "leaked",
    opponent: "PIT",
    opponentName: "Pittsburgh Steelers",
    side: "away",
    date: "2026-09-13",
    kickoffET: "1:00 PM ET",
    tv: "TBD",
    venue: "Acrisure Stadium, Pittsburgh",
    note: "Leak · Steelers Week 1 host per multiple national reports. Awaiting 8 PM ET confirmation.",
  },
  {
    week: 9,
    status: "confirmed",
    opponent: "CIN",
    opponentName: "Cincinnati Bengals",
    side: "home",
    date: "2026-11-08",
    kickoffET: "9:30 AM ET",
    tv: "NFL Network",
    venue: "Santiago Bernabéu, Madrid",
    note: "International · Falcons HOST Bengals at Real Madrid's Bernabéu. Bijan vs. Burrow / Chase.",
  },
];

// =========================================
// 2025 SEASON RECAP
// =========================================
export const SEASON_RECAP_2025 = {
  record: "8-9",
  divisionFinish: "3rd NFC South",
  playoffsResult: "Missed · 7th straight",
  pointsFor: 378,
  pointsAgainst: 392,
  netDifferential: -14,
  storylines: [
    "Started 4-9 before winning final four games",
    "Michael Penix Jr. took over as QB1 midseason",
    "Penix tore ACL Week 11 vs Seahawks (season-ending)",
    "Fired HC Raheem Morris + GM Terry Fontenot after Week 18",
    "Kevin Stefanski + Ian Cunningham hired to lead reset",
  ],
  keyStats: {
    bijanRushYds: 1478,
    bijanTDs: 14,
    londonRecYds: 1271,
    batesTackles: 98,
    batesInts: 3,
    walkerSacks: 5.5,
    dorlusSacks: 8.5,
  },
};

// =========================================
// RESULTS 2025 — final full season
// =========================================
export const RESULTS_2025 = [
  { date: "2025-09-07", opp: "TB", home: false, atlScore: 17, oppScore: 22, result: "L" },
  { date: "2025-09-14", opp: "PHI", home: true, atlScore: 22, oppScore: 21, result: "W" },
  { date: "2025-09-21", opp: "KC", home: false, atlScore: 17, oppScore: 22, result: "L" },
  { date: "2025-09-28", opp: "NO", home: true, atlScore: 26, oppScore: 24, result: "W" },
  { date: "2025-10-05", opp: "WAS", home: true, atlScore: 20, oppScore: 27, result: "L" },
  { date: "2025-10-12", opp: "BUF", home: false, atlScore: 17, oppScore: 34, result: "L" },
  { date: "2025-10-19", opp: "SF", home: true, atlScore: 20, oppScore: 17, result: "W" },
  { date: "2025-10-26", opp: "TB", home: true, atlScore: 24, oppScore: 27, result: "L" },
  { date: "2025-11-10", opp: "NO", home: false, atlScore: 21, oppScore: 24, result: "L" },
  { date: "2025-11-17", opp: "DEN", home: true, atlScore: 13, oppScore: 20, result: "L" },
  { date: "2025-11-24", opp: "SEA", home: false, atlScore: 10, oppScore: 27, result: "L" },
  { date: "2025-12-01", opp: "LAC", home: true, atlScore: 17, oppScore: 23, result: "L" },
  { date: "2025-12-08", opp: "MIN", home: false, atlScore: 14, oppScore: 28, result: "L" },
  { date: "2025-12-14", opp: "LV", home: true, atlScore: 31, oppScore: 17, result: "W" },
  { date: "2025-12-21", opp: "ARI", home: false, atlScore: 28, oppScore: 21, result: "W" },
  { date: "2025-12-28", opp: "CAR", home: true, atlScore: 34, oppScore: 13, result: "W" },
  { date: "2026-01-04", opp: "NO", home: false, atlScore: 27, oppScore: 24, result: "W" },
];

// =========================================
// NFC SOUTH 2025 FINAL STANDINGS
// =========================================
export const NFC_SOUTH_STANDINGS_2025 = [
  { team: "Tampa Bay Buccaneers", code: "TB", wins: 11, losses: 6, pct: 0.647, divisionFinish: 1 },
  { team: "New Orleans Saints", code: "NO", wins: 9, losses: 8, pct: 0.529, divisionFinish: 2 },
  { team: "Atlanta Falcons", code: "ATL", wins: 8, losses: 9, pct: 0.471, divisionFinish: 3, isFalcons: true },
  { team: "Carolina Panthers", code: "CAR", wins: 5, losses: 12, pct: 0.294, divisionFinish: 4 },
];

// =========================================
// NEWS DIGEST — refreshed daily by scheduled task
// =========================================
export const NEWS_DIGEST = {
  generatedAt: "2026-05-14T13:30:00Z",
  sources: [
    "Atlanta Falcons Official", "ESPN", "NFL.com", "The Falcoholic",
    "Bleacher Report", "Pro Football Rumors", "SI Falcons", "NBC Sports",
    "Yahoo Sports", "Spotrac", "Heavy.com", "CBS Sports", "AJC",
    "The Athletic", "Pro Football Network", "FBSchedules", "BloggingDirty",
    "Saturday Down South", "Pro Football Talk", "Yardbarker", "PFF",
    "Locked On Atlanta", "FanSided", "ClutchPoints", "TWSN", "Over The Cap",
    "National Today", "Freedom 96.9", "Athlon Sports", "Audacy 92.9 The Game",
    "Kicks 99", "BetMGM", "Wikipedia", "Bleeding Green Nation",
    "Sporting News", "RAS.football", "NFL Trade Rumors", "WalterFootball",
    "Front Office Sports", "AtlAllDay", "FootballScoop", "NFLPA", "KNBR",
    "NBC Miami", "Today in Miami", "Awful Announcing", "On3",
    "Rolling Out", "BVM Sports", "WHEC", "ABC7 Chicago", "FieldLevelMedia",
    "WSB-TV", "Atlanta News First", "TigerNet", "MadameNoire",
    "College Football Network", "AOL", "The Spun", "Business Upturn",
    "Sportskeeda", "Sharp Football", "Draft Sharks", "Ourlads",
    "Schedule2026", "NFL Analysis Network", "Real Madrid",
    "Sports Brackets", "The Sun", "Breezy Scroll",
    "Bengals.com", "FOX19", "On Location", "Southern Sports Today",
    "Behind The Steel Curtain", "Steelers Depot", "The Big Lead",
    "Sportsbook Review", "DAZN", "Sports Media Watch",
  ],
  topics: [
    {
      title: "SCHEDULE REVEAL NIGHT — Full 2026 calendar TONIGHT 8 PM ET (NFL Network / ESPN2 / NFL+); Falcons AT Steelers Week 1 leaked (Sun Sep 13, 1 PM ET)",
      detail: "Yahoo / CBS Sports / Behind The Steel Curtain / Steelers Depot / NFL.com / The Falcoholic (Wed–Thu May 13–14): the 272-game schedule drops at 8 PM ET tonight on NFL Network / ESPN2 / NFL+ / ESPN App. The biggest Falcons leak hit overnight — Atlanta will OPEN at the Pittsburgh Steelers on Sunday Sep 13, 1 PM ET. That means no primetime Week 1 spotlight but a road test at Acrisius vs. a Steelers team that just signed Tomlin to another extension. Falcons' 17 opponents are locked — HOME (9): CAR, NO, TB, BAL, CHI, CIN, DET, KC, SF · AWAY (8): CAR, NO, TB, CLE, GB, MIN, PIT, WAS. Bye week, primetime slots and the Madrid travel pattern all hit at 8. Seahawks-Patriots is rumored to open the league on Thursday night.",
      category: "general",
    },
    {
      title: "Madrid locked at Week 9 — Falcons HOST Bengals Sun Nov 8, 9:30 AM ET at Bernabéu, on NFL Network",
      detail: "ESPN / NFL.com / Bengals.com / Atlantafalcons.com / Yahoo / NBC PFT (Wed May 13, 9 AM ET): the NFL's international slate dropped yesterday on GMFB and confirmed Atlanta will HOST the Cincinnati Bengals (Joe Burrow, Ja'Marr Chase, Tee Higgins) in Madrid on Sunday Nov 8 — a 9:30 AM ET kickoff at Santiago Bernabéu, the 70-year home of Real Madrid CF, airing on NFL Network. Bengals' first Madrid trip and their first international game in seven years. President & CEO Greg Beadles: 'We are truly honored and deeply grateful for the opportunity to host the Cincinnati Bengals at the Bernabéu.' Atlanta now has six prior international games (Toronto '13, London '14/'21/'23, Berlin '25). On Location packages already live. Bijan vs. Burrow showcase officially on the calendar.",
      category: "games",
    },
    {
      title: "OTAs T-4 — Phase 3 opens Mon May 18, first competitive 11-on-11 reps of Stefanski era; Penix tracked into first-week throwing reps",
      detail: "Atlantafalcons.com / ESPN / NFL.com / SI Falcons (May 12–14): Phase 3 OTAs open at Flowery Branch this Monday — Atlanta's full slate is May 18–19, 21, 26–27, 29, plus June 8–9, 11. First on-field 7-on-7, 9-on-7 and 11-on-11 reps of the Stefanski era (no live contact). Penix saw individual drills last week throwing to London during Phase 2; the Monday window is the first he can run with the offense in a team setting. Stefanski's repeat line on Penix is 'right where he needs to be' but he's still 'not so focused on timetables.' Tua's 1yr/$1.3M bridge gets the early OTA QB1 reps. Mandatory veteran minicamp June 16–18.",
      category: "coaching",
    },
    {
      title: "Branch flies to LA TODAY for NFLPA Rookie Premiere — Atlanta's lone invite, May 14–17 in Los Angeles, returns for OTAs Mon",
      detail: "NFLPA / Yahoo Sports / SI Falcons / Athlon / Atlantafalcons.com (May 12–14): R3 WR Zachariah Branch boards for Los Angeles today as the only Falcons rookie on the 42-name 2026 NFLPA Rookie Premiere invite list. The annual brand-and-photo summit runs May 14–17 — trading-card photoshoots, autograph signings, jersey unveilings, group-licensing orientation — and overlaps the full schedule reveal tonight. 20 of 42 invites are wide receivers, confirmation the league sees Branch as a Day-1 producer despite slipping to #79. UGA junior line: 81/811/6 with 4.35 speed. Branch drew rookie-camp raves: speed in route-breaks Day 1, stopping to shake every media member's hand post-practice, and revealing Cash Jones is making the position switch to slot WR. Back at Flowery Branch for Phase 3 Monday.",
      category: "general",
    },
    {
      title: "Penix throwing through Phase 2 — Stefanski 'right where he needs to be,' no timetable; QB battle officially opens Monday with first 11-on-11s",
      detail: "ESPN / NFL.com / NBC PFT / The Falcoholic / Atlantafalcons.com / SI Falcons (May 9–14 sweep): Michael Penix Jr. is throwing through Phase 2 at Flowery Branch, including the headline rookie-minicamp session to Drake London — visible six-month-post-op step for his Nov 16 ACL reconstruction. Stefanski's repeat line: 'right where he needs to be.' Asked for a timetable: 'not so focused on timetables just yet,' with more clarity expected near camp. President of Football Matt Ryan added 'Mike's in a good spot right now' but cautioned 'we don't really know what to expect at the beginning of training camp.' Penix has publicly aimed at Week 1; the team hasn't endorsed that target. Tua's 1yr/$1.3M bridge takes the early OTA QB1 reps Monday. Standard ACL window is 9–12 months; real competition lives in training camp.",
      category: "injuries",
    },
    {
      title: "8 post-minicamp roster moves — Blacklock, Walton, Robinson, Rayner signed off tryouts; Stille, Thompkins, Washington, Frazier released",
      detail: "Atlantafalcons.com / Yahoo Sports / SI Falcons / NFL Trade Rumors / Yardbarker / NBC PFT / The Falcoholic / BVM Sports (Mon May 11–Tue May 12): four tryout invites earned NFL contracts after a strong rookie minicamp — DT Ross Blacklock (27, 2020 R2 TCU, vet stops w/ HOU/MIN/JAX/TEN/IND/NYG; unsigned in 2025), OL Brandon Walton (28, FAU 2020 UDFA, 5 years experience), G Layden Robinson, and LB Daveren Rayner. Four corresponding releases: DL Ben Stille, RB Carlos Washington Jr., WR Deven Thompkins, and rookie TE Brandon Frazier. Blacklock is the headliner — reunites with Stefanski (their Minnesota OC overlap) and gives Cunningham veteran insurance for the IDL room that's been flagged all spring as the biggest open hole.",
      category: "free-agency",
    },
    {
      title: "Rookie minicamp wrap — three-day camp closed Sun May 10, Stefanski 'goal was to learn our system,' Branch / Perkins headlined on-field",
      detail: "Atlantafalcons.com / AJC / SI Falcons / The Falcoholic / Yardbarker / Atlanta News First (Fri May 8 → Sun May 10): the three-day rookie minicamp closed Sunday at Flowery Branch after running with 46 bodies on field — six draftees, 14 UDFAs, 23 tryout invites, two NFL-vet tryouts (Blacklock + Walton confirmed Mon), three returning Falcons. Stefanski's AJC line: 'Goal is to learn our system' — system install and facility orientation, not depth-chart sorting. Stefanski also confirmed he's not afraid to play rookies: 'If a rookie earns a role and Week 1 he's ready to go, then he'll be out there.' UGA UDFA RB Cash Jones repped at slot WR all weekend — confirmed by Branch — pointing to a Cordarrelle-style positionless role. R6 LB Harold Perkins Jr. went through a full slate Saturday despite his ACL-recovery flag.",
      category: "coaching",
    },
    {
      title: "Pearce diversion finalized last week — six-month program; NFL discipline expected 'in the fairly near future' per Rapoport",
      detail: "NFL.com / NBC PFT / The Falcoholic / Heavy / CBS Sports / Rolling Out / SI Falcons / PFR (May 7–11) confirm James Pearce Jr.'s pretrial intervention agreement was finalized Thursday in Miami-Dade Court: six months of therapy, drug testing, and a stay-away order from WNBA's Rickea Jackson. All three felony counts (aggravated battery w/ deadly weapon, fleeing, resisting) plus the misdemeanor stalking count dismiss on clean completion. League discipline runs separately — Rapoport: 'the league will likely act with this resolution in the fairly near future.' Baseline for personal-conduct domestic violence is six games and NFL discipline does not require a criminal conviction. With Ebiketie gone to PHI, the edge room behind Walker / Ojulari / Ebukam / Thomas / Trice / Malone is thin on proven snaps.",
      category: "general",
    },
    {
      title: "Avieon Terrell limited at rookie camp — aunt Giselle Perry killed Wed in Decatur Kroger lot; CB2 reps pushed to OTAs",
      detail: "WSB-TV / Atlanta News First / atlantafalcons.com / ESPN / TigerNet (May 8–10) report aunt Giselle Perry was killed Wed May 6 around 3:20 PM at the Wesley Chapel Rd. Kroger when a driver suffering a medical emergency crashed into her parked car at high speed. A.J. and Avieon Terrell are family. Stefanski opened Friday's rookie-camp presser dedicating his thoughts to the Terrell family and confirmed Avieon plus R6 DT Anterio Thompson would be held out of drills due to injury but kept in the facility. Per ESPN's Marc Raimondi, Avieon told him he's 'feeling 100 percent.' He did limited work Day 1 and stayed in installs/meetings the rest of the weekend. CB2 competition with Mike Hughes officially pushes to OTAs May 18.",
      category: "injuries",
    },
    {
      title: "Phase 2 Week 2 wraps Friday — Stefanski's 'identity' install; Tommy Rees calling plays, three-man Browns coaching reunion locked",
      detail: "Atlantafalcons.com / FootballScoop / CBS Atlanta / SI Falcons / Blogging Dirty / NBC PFT (May 4–14): Phase 2 opened Mon May 4 — non-contact walkthroughs and individual drills only. Today (Thu May 14) is the second-to-last day of Phase 2 before OTAs Monday. Tori McElhaney's through-line for Stefanski's program: 'X's and O's, techniques, fundamentals, identity.' Stefanski confirmed publicly he's 'very comfortable' with OC Tommy Rees calling plays in 2026. Rees was Browns TEs coach 2024 → OC mid-2025 — three Browns assistants reunited (Rees, OL Bill Callahan, QB coach Alex Van Pelt). System DNA: play-action, under-center, wide-zone foundation blended with gap concepts (suits Bijan's Texas pedigree). Penix-Rees adjustment: less pistol/shotgun than Penix has run his whole career.",
      category: "coaching",
    },
    {
      title: "Drake London extension still 'top of mind' — Athletic's Kendall projects 4yr/$135M ($33M+ APY), Garrett Wilson comp",
      detail: "Heavy / ClutchPoints / Yahoo / SI Falcons / NBC PFT / The Athletic (via TWSN) / atlantafalcons.com (May 7–11 sweep): Cunningham's post-draft 'top of mind' line on London is unchanged but no signed deal yet. London is on the $16.8M fifth-year option for 2026 — final year of the rookie deal. The Athletic's Josh Kendall this week: 'echo Garrett Wilson at 4 years/$130M, could project at 4yr/$135M.' Kendall's market read pushes London into upper-tier WR money — $33M+ APY — just behind JSN ($42.15M), Chase, Jefferson, and CeeDee Lamb. ClutchPoints' insider demand also lands at 4yr/$135M. Org-stated goal: signed before training camp opens July 22. No reported momentum into schedule-release week.",
      category: "contracts",
    },
    {
      title: "Bijan extension on the way — Schefter 'this offseason'; National Today / BloggingDirty cluster at 3yr/$69–75M ($23–25M APY)",
      detail: "Schefter (via The Falcoholic) plus PFR / National Today / NFL Analysis Network / DraftSharks / Yardbarker (May 7–11): Bijan extension is expected to land this offseason — Schefter on his podcast: 'Between Gibbs, Bijan, and Achane, they're about to completely reset the RB market.' National Today's working framework lands at 3yr/$69M ($23M APY) floor / 3yr/$75M ($25M AAV) ceiling, making him the highest-paid RB in NFL history. Apr 12 fifth-year option ($11.32M for 2027) is openly a placeholder per beat writers — cheapest fifth-year option in his entire R1 class given the All-Pro résumé (1,478 rush / 820 rec / 16 TDs / scrimmage-yard leader). Detroit closing Jahmyr Gibbs first is the only realistic market-reset risk.",
      category: "contracts",
    },
    {
      title: "Bates wants to retire a Falcon, no extension talks yet — final year of his $64M deal, void in 2027",
      detail: "PFR / Yardbarker / Over The Cap / SI Falcons (Apr–May): All-Pro safety Jessie Bates publicly said he wants to spend the rest of his career in Atlanta — but the team has not engaged in extension talks as of April 2026. Bates is entering the final year of his 4yr/$64.02M deal (2026, $24.8M cap hit, $16M AAV — 8th-highest among safeties). Contract has a void year in 2027, marking him as an extension candidate this offseason. Three picks last season pushed his career INT total to 27, his third 2nd-team All-Pro nod. With London and Bijan stacked ahead of him in Cunningham's 'wave' contract queue, a Bates deal is more likely a fall conversation than a summer one.",
      category: "contracts",
    },
    {
      title: "IDL still Cunningham's open need — Blacklock joins room off Mon tryout, Smith / Hand / Williams / Thompson still no proven 1-tech",
      detail: "Falcoholic / SI Falcons / ESPN beat trackers / atlantafalcons.com (May 7–12): interior defensive line remains the biggest remaining roster hole heading into OTAs even after Mon's Ross Blacklock signing off the tryout. Cunningham flagged the 'second wave' window weeks ago. Onyemata to NYJ and Orhorhoro to JAX (for Maason Smith) thinned the room. The 2026 rotation — Maason Smith, Da'Shawn Hand (1yr/$3M), Chris Williams (Cleveland holdover), R6 #208 Anterio Thompson, plus UDFA DT Carlos Allen and now vet Blacklock — still lacks a proven 1-technique. Another veteran depth signing remains a live transaction window.",
      category: "free-agency",
    },
    {
      title: "Pitts trade chatter fully dead — no TE drafted, voluntary attendance, $15M tag cashed, Rees building 12-personnel around him",
      detail: "Blogging Dirty / Yardbarker / ClutchPoints / Heavy / SI Falcons / AJC: Atlanta did not draft a tight end, Pitts cashed the $15.045M franchise tag and showed for voluntary minicamp, and Cunningham's posture has shifted from 'willing to listen' to using Pitts as the centerpiece of Rees' 12-personnel install. Stefanski's known affinity for the TE position locks the read: Pitts isn't moving. Schefter's pre-draft 'multiple-mention' chatter has gone dark for three-plus weeks. The trade window technically reopens through final cuts; the practical window has closed.",
      category: "contracts",
    },
    {
      title: "Calendar — Full schedule reveal TONIGHT 8 PM ET · OTAs Mon T-4 · Madrid Week 9 locked · Rookie Premiere through Sat",
      detail: "Day-of (Thu May 14): the full 272-game 2026 schedule drops at 8 PM ET on NFL Network / ESPN2 / NFL+. Falcons-at-Steelers Week 1 (Sun Sep 13, 1 PM ET) and Falcons-vs-Bengals Madrid Week 9 (Sun Nov 8, 9:30 AM ET) are the only locks pre-reveal. Bye week, primetime slots and the rest of the calendar all hit at 8. Phase 2 Week 2 closes Friday at Flowery Branch. Branch is in Los Angeles tonight through Saturday at NFLPA Rookie Premiere. Phase 3 OTAs open Mon May 18 (Atlanta's slate: May 18–19, 21, 26–27, 29, June 8–9, 11) — first competitive 11-on-11 reps of the Stefanski era. Mandatory veteran minicamp June 16–18; dead period through Jul 21; training camp opens Jul 22.",
      category: "general",
    },
  ],
};
